### ISSUE TITLE
Diseñar el layout principal de la aplicación

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#1]
Diseñar el layout que contendrá las vistas de la aplicación. El diseño debe considerar los siguientes elementos:
- La barra de menú (parte superior de la página).
- Un contenedor central que contendrá las vistas

**Comment by bordonwork** [comment]
Diseñar el layout que contendrá las vistas de la aplicación. El diseño debe considerar los siguientes elementos:

- La barra de menú (parte superior de la página).

- Un contenedor central que contendrá las vistas

**Comment by rofaccess** [comment]
**Layout principal**

![screenshot from 2016-03-05 13-04-03](https://cloud.githubusercontent.com/assets/2489653/13549649/ddd010a2-e2e8-11e5-9c58-c8acdba8997b.png)

**Ejemplo de menus con diferentes combinacion de colores**
Entre los integrantes del grupo se decidió adoptar el número 2

![screenshot from 2016-03-05 13-04-48](https://cloud.githubusercontent.com/assets/2489653/13549656/f79703ec-e2e8-11e5-99e3-37347f3fa4ae.png)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 2.5 horas

**Comment by louvelaz** [comment]
@rofaccess Faltaria una pestaña de Ayuda o Manual, y una pestaña de Turnos

**Comment by rofaccess** [comment]
![menu 2](https://cloud.githubusercontent.com/assets/2489653/13551789/2a1afb3e-e325-11e5-8938-345a716e31ad.png)

**Nota:** El ícono de interrogación en la esquina superior derecha será para acceder al manual
**Tiempo Utilizado:** 0.5 horas
