### ISSUE TITLE
Diseñar el ABM de Empleados

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#10]
Se requiere hacer el diseño para las vistas del ABM de Empleados, esto incluye:
- Nuevo(y editar) empleado.
- Listar empleados.

**Comment by rofaccess** [comment]
**Lista de Empleados**

![5 empleados](https://cloud.githubusercontent.com/assets/2489653/13550912/7fb4e4d8-e307-11e5-9402-50a88996b04c.png)

**Agregar Empleado (Valido también para editar)**

![6 nuevo empleado](https://cloud.githubusercontent.com/assets/2489653/13550917/9f222826-e307-11e5-8f20-f6b7053f2444.png)

**Comment by rofaccess** [comment]
**Breve Descripción**
**Listado de Empleados**
1. En la interfaz donde se lista el empleado se puede buscar por cualquier campo de la tabla.
2. Hay muchos datos que se pueden mostar en la tabla. Se tratará de mostrar solo los que se considere mas importantes.
3. La lupa con el simbolo "+" deberá desplegar una sección de busqueda avanzada (Esto se diseñara e implementará en algún momento más adelante)
4. El botón agregar empleado abrirá un formulario para cargar los datos a través de ajax

**Agregar Empleado**
Se clasificó en Datos Personales, Datos de Contacto,  y Datos laborales, porque eran muchos registros. Esta clasificación se podría expresar también en tabs

![screenshot from 2016-03-05 19-28-40](https://cloud.githubusercontent.com/assets/2489653/13550962/8cb22d16-e308-11e5-847e-b4ae3fb549f3.png)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 1.5 horas

**Comment by louvelaz** [comment]
@rofaccess El Horario no debería ser un String.

**Comment by rofaccess** [comment]
![screenshot from 2016-03-05 23-12-40](https://cloud.githubusercontent.com/assets/2489653/13551894/d1437696-e327-11e5-9ef0-52dd518e4e82.png)

**Notas:**
1. Agruegue unos cuantos iconos + ahora.
2. Fue un pequeño error. El horario se selecciona de un select, para esto se presupone que hay horarios precargados (Ej: "05:00 a 13:00", "12:00 a 17:00", "05:00 a 12:00 y 13:00 a 15:00" , etc. ) El simbolo + abre un pequeño modal para cargar otro horario a la lista.
3. Todos los símbolos + sirven para agregar, en el caso de sexo tal vez no sea necesario (hoy día nunca se sabe), en cuanto a estado civil, tipo de empleado y cargo, es posible que se requieran más item, por eso se tiene el icono +.

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 10 minutos
