### ISSUE TITLE
Agregar la opción Logout a la barra de menú

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#11]
Depende del issue #3 y #6 
Se requiere agregar el link para hacer logout en la barra del menú superior a fin de que el usuario logueado pueda cerrar su sesión.

Consultar la [documentación](https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template) de devise para más información

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 30 minutos

**Comment by rofaccess** [comment]
Esta tarea ya se integró a la rama development
