### ISSUE TITLE
Diseñar interfaz de horario de Empleado

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#12]
Se requiere:
- El diseño debe especificar una manera de seleccionar un empleado, ya sea por su nombre y/o ci.
- Se muestra una tabla tipo calendario, cuyas filas contienen horas y cuyas columnas contienen días, y con clicks en las celdas se habilita o no ciertas horas en ciertos días.

**Comment by Lesfig** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6785488/13690041/13ce0d5e-e70c-11e5-8d0c-baee1c3e1d4a.png)

**Comment by Lesfig** [comment]
Obs: es un diseño que puede variar al ser implementado...

Breve descripción:
 Cada empleado cuenta con un horario por día y hora, para poder ver,agregar o editar dicho horario el usuario deberá ir a la interfaz de horario por empleado, en el cual podrá ver el horario de un profesional en particular, plasmada en una tabla cuyas filas son las horas y las columnas los días, para agregar o eliminar cierto horario solo basta con dar click en la celda correspondiente a la hora y día que el profesional brindará o no servicio en la Cenade y así finalmente guardarlo

**Comment by louvelaz** [comment]
@Lesfig Se debe indicar en algún costado el color que representa a la hora que si brindara servicio, y el color que representa cuando no. Ejemplo: blanco para las hora que no trabaja, celeste para las que si. Adjunto imagen de ejemplo

![ejemplo](https://cloud.githubusercontent.com/assets/6853236/13693180/1b160196-e727-11e5-9e06-2448d514dd96.jpg)

**Comment by Lesfig** [comment]
![untitled 1](https://cloud.githubusercontent.com/assets/6785488/13719838/e64f6a92-e7da-11e5-8889-2d0df1b9c921.png)

**Comment by Lesfig** [comment]
Así quedaría la interfaz de horario de empleado, con las sugerencias de @louvelaz

**Comment by Lesfig** [comment]
Luego de las Modificaciones la interfaz quedará así (ver imagen), para modificar el horario se desplegará un ventana modal para agregar cierta fecha al horario con sus respectivas horas de atención
![screenshot_2](https://cloud.githubusercontent.com/assets/6785488/13799845/04a93f98-eb02-11e5-8af7-eab2fbc206f4.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/6785488/13799849/0bbb72ce-eb02-11e5-89fe-1b375edfbb63.png)

**Comment by louvelaz** [comment]
@Lesfig  
- Falta botón eliminar y editar
- Faltaría agregar el diseño de la interfaz de los empleados que trabajan en horarios fijos, de lunes a viernes por ejemplo. 
- Falta agregar buscador o filtros por fechas 

Sugerencia: El botón podría llamarse Nuevo Horario en vez de Modificar Horario

**Comment by Lesfig** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/6785488/13852019/2211f9c4-ec3f-11e5-8f37-a5c6749377a2.png)

Los iconos de la parte superior derecha son para agregar, listar, imprimir y salir de la página

**Comment by Lesfig** [comment]
Debido a los nuevos requerimientos se cierra el issue #12
