### ISSUE TITLE
Implementar la configuración para setear los Datos de la empresa

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#14]
.Se requiere
- Crear la migración para la tabla configuración, cuyos
  atributos son nombre_empresa, logo_empresa, logo_sesion_empresa.
- Implementar un formulario que permita establecer el nombre de
  la empresa, y para alzar la imagen para el logo del menú principal y
  para el logo que se muestra al iniciar la sesión.
   Notas:
               1. El formulario tiene que aparecer cuando se hace
  click en Datos de la empresa del menú configuración.
               2.El formulario, no se debe mostrar dentro de un
  modal. El modal solo se usa para nuevo y editar en los abm.
               3. Se puede usar la gema paper_trail para manejar las
  imágenes de los logos.

**Comment by rofaccess** [comment]
Para testeo en: http://cenade-test.herokuapp.com/configuraciones/1/edit

**Comment by louvelaz** [comment]
@Lesfig 
- Al seleccionar una imagen nueva, esta tiene que adaptarse a un tamaño prefijo dentro del formulario, no agrandarse a su tamaño original sea cual sea su resolución.

![conf test cenade 1 resultado](https://cloud.githubusercontent.com/assets/6853236/14083247/972e2d94-f4e2-11e5-8d6e-9cfa85bcf294.jpg)
- En la barra de menu el logo se ve muy pequeño y aplastado

![conf test cenade 1 resultado 2 muy chico](https://cloud.githubusercontent.com/assets/6853236/14083254/a51c8964-f4e2-11e5-8da4-df97be519de4.jpg)

**Comment by louvelaz** [comment]
@Lesfig Quedaría pendiente ver donde se alojarían las imagenes
