### ISSUE TITLE
Implementar el ABM de facturas

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#15]
Se requiere
- Crear las migraciones para las tablas paciente, turno,
  factura y factura_detalle.
- Implementar el listado de facturas en una tabla, por cada
  fila se debe mostrar la opción de editar y eliminar factura.
- Implementar el formulario de editar y agregar factura, la
  cual se despliega en un modal.
- Implementar las validaciones correspondientes acorde a los
  campos de los formularios de editar y agregar.
  Notas:
  1. Se presupone que la tabla de personas ya se creó anteriormente,
     si no existe, se deberá crear la migración correspondiente, que deberá
     contener por lo menos id, nombre y ci

**Comment by bordonwork** [comment]
Este requerimiento se ha excluido del proyecto. @afocampos y @mirtara

**Comment by afocampos** [comment]
@bordonwork porqué fue sacado? ya no lo necesitan? o no era luego parte de los requerimientos?

**Comment by bordonwork** [comment]
Luego de la última reunión con la gente del Cenade quedó excluido
