### ISSUE TITLE
Documentar las Políticas de Turnos

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#20]
Se deben agregar, actualizar y/o corregir las políticas de turnos concernientes al sistema en los siguientes aspectos:
### Turnos
- Cuándo se realizan los turnos?. Tienen un costo o no?. Está este costo administrado por el sistema?.
- Se pueden cancelar los turnos?. En cuáles casos y en cuáles no?. Se realizará devolución de dinero?.
- Qué tipos de turnos existen?.
### Importante
- Las preguntas formuladas en el apartado anterior sirven de guía para redactar el documento. Éstas no pretenden limitar/excluir/agregar las políticas que el equipo considere o no necesarias.
- El formato de las políticas debe ir acorde al formato utilizado en las documentaciones ya existentes, sin embargo se recomienda utilizar un formato similar al proveído.
  ![image](https://cloud.githubusercontent.com/assets/3639650/13990758/4119f510-f0f4-11e5-8bd0-3aa13ba7a5a1.png)
- Cuando se tenga una versión del documento, éste debe ser referenciado (en formato de imagen, o un link al documento) en los comentarios de esta tarea a fin que puedan hacerse las recomendaciones, correcciones y preguntas pertinentes.

**Comment by Lesfig** [comment]
# Políticas de Turnos

## Asignar turno

1-  Un turno puede ser asignado al paciente, por un secretario o empleado cuyo rol tenga los permisos correspondientes para realizar dicha tarea.
2-  El paciente podrá disponer de un turno en el área que desea si y sólo si, hay cupos disponibles para esa área y la misma esté disponible ese día, para saber esto solo bastará con especificar el área a consultar, y automáticamente la secretaria verá los horarios de atención de la especialidad, y si no cuenta con cupos disponibles un mensaje con la advertencia. También hay excepciones como el área de neurología, solamente en el área de neurología se podrán reservar turnos en días previos al horario de atención, también se podrán cancelar los turnos pasando automáticamente ese turno para la siguiente fecha. (Así es como se manejan en la CENADE, pero no sé si limitaremos eso en el sistema de que solo en Neurología se pueda reservar y cancelar turnos) 
3-  El paciente para acceder al turno debe estar previamente registrado en el sistema, para saber si está o no registrado, la secretaria deberá escribir la C.I. del paciente, si es que lo tiene (debido a que hay menores sin CI), si no hay coincidencia deberá registrar al paciente, si no tiene CI el nombre y apellido del paciente,  si no está la secretaria inmediatamente tomará los datos del paciente para registrarlo, para luego dar el turno al paciente en el área
4-   Los montos por área serán registrados en alguna parte del sistema(sugerencia en el abm de empleado, ya que hay algunas excepciones en la que el profesional de un área cobra un monto y otro profesional del mismo área cobra otro monto, por ende depende del profesional y no del área).
5-  La secretaria debe especificar si el paciente abona o no, el monto impuesto. De ser sí la respuesta debe especificar el número de factura el cual emite, el monto es automático de acuerdo al monto estipulado por el profesional del área a ser consultada. Y si no el paciente igualmente podrá reservar un turno. 
6-      No se realiza devoluciones de dinero en ninguno de los casos.
7-  Si el sistema no tiene ficha del paciente en el área a consultar, éste lo generará automáticamente.
8-  El orden en el cual serán atendidos dependerá del orden de llegada de cada paciente, luego el profesional tendrá a disposición una lista de pacientes a ser atendidos en el orden de llegada.

**Comment by Lesfig** [comment]
@rofaccess y @KariSanabria comenten :) !!

**Comment by Lesfig** [comment]
Bueno según los comentarios, edite mis políticas

# Políticas de Turnos

## Asignar turno

1- Un turno puede ser asignado al paciente, por un secretario o empleado cuyo rol tenga los permisos correspondientes para realizar dicha tarea.
2- El paciente podrá disponer de un turno en el área que desea si y sólo si, hay cupos disponibles para esa área y la misma esté disponible ese día. Excepto el área de neurología, solamente en el área de neurología se podrán reservar turnos en días previos al horario de atención, también se podrán cancelar los turnos pasando automáticamente ese turno para la siguiente fecha. (Así es como se manejan en la CENADE, pero no sé si limitaremos eso en el sistema de que solo en Neurología se pueda reservar y cancelar turnos) 
3- El paciente para acceder al turno debe estar previamente registrado en el sistema, si no está registrado la secretaria inmediatamente tomará los datos del paciente para registrarlo, para luego dar el turno al paciente en el área
4- Los montos dependerán de los  profesionales que atenderán y no del área.
5- El paciente deberá abonar el monto estipulado por el servicio que desee, dependiendo del profesional, siempre y cuando éste pueda pagar dicho monto, si no lo puede igual le será reservado un turno,exonerándole el monto.
6- No se realiza devoluciones de dinero en ningún caso.
7- El orden en el cual serán atendidos los pacientes dependerá del orden de llegada de cada paciente para reservar el turno.
8- Una persona podrá reservar dos o más turnos de distintas áreas, siempre y cuando se cumpla con el punto 2.

9- EL CI no será un dato necesario del paciente, ya que puede ser un paciente sin CI,

**Comment by rofaccess** [comment]
Mi opinión:
En el 2: Creo que hay que generalizar y no darle un trato especial a neurología. Nos facilitaría mucho el trabajo, si se pudiera especificar una fecha para ver disponibilidad de turno. Para los turnos disponibles solo en el día, se especifica la fecha del día (de hecho, debería ser un valor por defecto cuando se crea un turno), si el turno es para neurología, se especifica la fecha en que se atiende neurología. Tener la opción de cancelar turno para todas las áreas requiere solo de un atributo estado (nuevo, cancelado, etc) y nos evitamos tratos especiales. Que tal si (De nuevo con mis que tal), se decide que para odontología hay que reservar turnos tal como se hace con neurología, creo que los puntos que mencione cubrirían este caso.

En el 4, creo que los montos dependían del área y en algunos casos de profesional. Podriamos fijar un monto en la tabla de área, y un monto en la tabla de profesional, y que el monto del profesional tenga precedencia si es que tiene especificado un coste diferente al menciondo en la tabla de área.
Considerar el monto solo por profesional también es factible, pero obligaría a que al momento de registrar un profesional, siempre habrá que especificar su coste. Y puede ser que el coste sea fijo por área. Es cuestión de pensar cual es más conveniente, a nivel de modelo de datos, código e interfaz.

El resto creo que están bien.

**Comment by Lesfig** [comment]
# Políticas de Turnos

## Asignar turno

1- Un turno puede ser asignado al paciente, por un secretario o empleado cuyo rol tenga los permisos correspondientes para realizar dicha tarea.
2- El paciente podrá disponer de un turno en el área que desea si y sólo si, hay cupos disponibles para esa área en la fecha próxima, también se podrán cancelar los turnos, podrán pasar sus turnos automáticamente para la siguiente fecha si lo desean.
3- El paciente para acceder al turno debe estar previamente registrado en el sistema, si no está registrado la secretaria inmediatamente tomará los datos del paciente para registrarlo, para luego dar el turno al paciente en el área
4- Los montos dependerán del área y de los profesionales, siendo la prioridad el monto del profesional si es que lo tiene.
5- Hay dos tipos de montos por área, dependiendo del paciente. Si el paciente es derivado de ips, tiene un monto y si no, tiene otro monto. 
6- El paciente deberá abonar el monto estipulado por el servicio que desee, dependiendo del profesional, siempre y cuando éste pueda pagar dicho monto, si no lo puede igual le será reservado un turno,exonerándole el monto.
7- No se realiza devoluciones de dinero en ningún caso.
8- El orden en el cual serán atendidos los pacientes dependerá del orden de llegada de cada paciente para reservar el turno.
9- Una persona podrá reservar dos o más turnos de distintas áreas, siempre y cuando se cumpla con el punto 2.

10- EL CI no será un dato necesario del paciente, ya que puede ser un paciente sin CI.

11- Al crear una turno si el paciente no tiene ficha en el área a consultar, se lo generará automáticamente

Tiempo utilizado 2h:30m

**Comment by Lesfig** [comment]
Miren @rofaccess  y @KariSanabria, así quedó con la modificaciones sugeridas, y también agregué el punto 5, que se me había pasado anteriormente

**Comment by rofaccess** [comment]
Creo que faltaría esto, que ya habias puesto en el primer comentario:
7- Si el sistema no tiene ficha del paciente en el área a consultar, éste lo generará automáticamente
No se si debería ir aquí o en #21, o en ambos, ya que cuando se asigna el turno pues, pretendemos generar la ficha automáticamente.

Con lo demás estoy deacuerdo.

**Comment by Lesfig** [comment]
Tiempo utilizado 2h:30m
