### ISSUE TITLE
Documentar las Políticas de las Fichas

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#21]
Se deben agregar, actualizar y/o corregir las políticas de fichas concernientes al sistema en los siguientes aspectos:
### Fichas
- Se podrán eliminar fichas?. En cuáles casos y en cuáles no?. Cuánto tiempo se almacenarán las fichas?. 
- Se podrán modificar las fichas?. Podrá un paciente tener más de una ficha del mismo tipo?.
- Cuántos tipos de fichas existen?.
- Qué pasa en el caso de que se realice una carga errónea en una ficha?. Qué criterios deben seguirse para realizar las correcciones?.
### Importante
- Las preguntas formuladas en el apartado anterior sirven de guía para redactar el documento. Éstas no pretenden limitar/excluir/agregar las políticas que el equipo considere o no necesarias.
- El formato de las políticas debe ir acorde al formato utilizado en las documentaciones ya existentes, sin embargo se recomienda utilizar un formato similar al proveído.
  ![image](https://cloud.githubusercontent.com/assets/3639650/13990758/4119f510-f0f4-11e5-8bd0-3aa13ba7a5a1.png)
- Cuando se tenga una versión del documento, éste debe ser referenciado (en formato de imagen, o un link al documento) en los comentarios de esta tarea a fin que puedan hacerse las recomendaciones, correcciones y preguntas pertinentes.

**Comment by KariSanabria** [comment]
Defino aquí algunos de los puntos a tener en cuenta, aun no esta completa,pero estoy trabajando en ello.

**Políticas de las Fichas**
La ficha clínica es el documento más importante de un servicio, en el cual se registra la historia médica de una persona y su proceso de atención médica.
**Agregar Ficha**
1-  Antes de la creación de la ficha se debe verificar que el usuario no cuente con una ficha previa, utilizando el C.I del paciente, nombre o apellidos  o fecha de nacimiento, para la verificación.
2-  Donde realizar esta verificación? Se podría tener un listado de pacientes y allí hacer una búsqueda si el paciente ya tiene una ficha creada y verificar en que área la tiene.
3-  El sistema deberá emitir un mensaje en caso de que el paciente no se encuentre en el sistema.
4-  Una vez hecha la comprobación de los datos del paciente, si existe, el personal médico se encarga de actualizar la ficha del paciente ya teniendo los antecedentes del mismo.
5-  En caso de no tener una ficha el paciente, el personal médico se encarga de cargar los datos personales del paciente y crear la nueva ficha y especificar para que área fue creada la ficha.
6-  El sistema deberá emitir un mensaje de que la ficha se ha creado con éxito. 
7-  Hay que tener en cuenta que existe aproximadamente 10 fichas.
8-  No hay necesidad de que el paciente tenga más de una ficha por área, para ello solo se necesitaría actualizar cada consulta hecha por el paciente.
9-  Se podría tener un abm de consultas, donde el profesional de la salud crea una nueva consulta, seleccionando primeramente el paciente para quien se creara la consulta.
10- Directamente esta consulta tendrá relación con el paciente.
11- Los campos requeridos en algunas fichas son muy extensas, entonces se debe ver las que tienen más prioridad para cargar al sistema.
12- También tengo alguna duda de eliminar las fichas y en qué caso.
13- Las fichas existentes serian:
- Ficha Fonoaudiología
- Ficha Psicopedagogía
- Ficha Nutricional Pediátrica
- Ficha Nutricional Adultos
- Ficha Odontológica Menor
- Ficha Odontológica Adulto
- Ficha Fisioterapia Pediátrica
- Ficha Fisioterapia Adulto
- Ficha Pediatría

14- En caso de tener una carga errónea de datos, se tendrá la opción de editar los datos de las fichas.
15- Se podría tener un listado de las consultas para facilitar al profesional de la salud para tener un seguimiento.

Tiempo utilizado: 02H:00m

**Comment by KariSanabria** [comment]
@rofaccess @Lesfig si pueden opinar al respecto.

**Comment by bordonwork** [comment]
Es importante @rofaccess y @Lesfig  que opinen porque las fichas son cruciales.

**Comment by rofaccess** [comment]
Mi opinión:
En el 1 basta decir que "el paciente no puede tener más de una ficha del mismo tipo", ahora ¿como cumplimos la regla?: verificando que el paciente no tenga ya la ficha de cierto tipo, hay que centrarse en especificar la regla y no especificar como vamos a cumplirla. Aunque el 1 así como esta ya parece una regla a cumplir (Estoy confundido).

El 2 no debería ir aqui, si no en el feature de pacientes, por ejemplo que desde un show paciente te liste las fichas que ya tiene y te permita crear los que faltan.

Del 3 al 6 definen flujos que corresponden a una interfaz.

El 7 no es una regla, es más bien una observación o una nota

El 8, el paciente no debe tener más de una ficha por área. Lo siguiente "para ello solo se necesitaría actualizar cada consulta hecha por el paciente" seria una aclaración, observacion o nota.

El 9 describe algo que debe ir en el feature de atencion profesional o uno de consulta (Habíamos considerado que la consulta formaría parte del flujo de atención profesional).

En el 10, la consulta tiene relacion con una ficha, y la ficha con el paciente.

El 11 creo que describe lo que se debe considerar en alguna interfaz.

En el 12, la eliminación tiene que ver ya con la política de la institución con respecto a las fichas. 
Podriamos darles la opcion de enviar a un historial o de borrar físicamente.

El  13 es una observación, nota o aclaración.

En el 14 "se tendrá la opción de editar los datos de las fichas" seria la regla y una nota al respecto " Esto en caso de tener una carga errónea de datos por ejemplo "

El 15 describe algo que consideramos tener en el feature de atencion profesional

**Comment by rofaccess** [comment]
@bordonwork necesito tu opinión respecto a mi comentario anterior a #21 porque mis comentarios podrían estar equivocados, si es que estoy comprendiendo mal lo que se deberían definir en las políticas.

**Comment by bordonwork** [comment]
Si, de hecho las politicas son reglas generales que se aplicaran en el
sistema,  no deben incluir descripciones de flujos. Una politica de ficha
por ejemplo seria: "Todas las fichas se guardaran en la bd por un período x"

**Comment by KariSanabria** [comment]
@rofaccess de hecho en el enunciado mencione que era algunos de los puntos a tener en cuenta para definir las políticas de las fichas, confunde un poco a que exactamente se define política , pero varias puntos no eran reglas definitivamente, ademas pienso que en la política no queda demás mencionar lo que se debe considerar en la interfaz.
Tendré en cuenta tu punto de vista, para cambiar puntos de este borrador.

**Comment by rofaccess** [comment]
@KariSanabria 
Me lo tomé como si fueran las políticas ya (Por eso quería esperar a que alzaras algo más definitivo je je). 
Respecto a mencionar lo que se debe considerar en la interfaz, habría que hacerlo en los features, esto porque, varios feature tocan las fichas (Ej. Al crear un turno se crea una ficha si es que no hay, desde la interfaz de paciente se podria cargar fichas, desde la interfaz de atencion medica se puede editar fichas, etc.). 
Osea que si vas a pensar en interfaces vas a querer definir ciertas cosas que deberían ir en las documentaciones de los features, y, podrías terminar mencionando muchas interfaces aquí.

A mi me resulta más fácil pensar en el flujo de un feature, y de ahí identifico las políticas, tal vez sea un mál hábito, espero que no te esté pasando lo mismo.

**Comment by KariSanabria** [comment]
**# Políticas de las Fichas**
**## Crear Fichas**
1-	Las fichas pueden ser creadas por el personal de la salud o cualquier otro empleado cuyo rol permita realizar dicha tarea Ej: la secretaria
2-	Cada paciente debe tener una ficha una vez hecha la consulta.
3-	El paciente no debe tener más de una ficha del mismo tipo. 
4-	Para crear una nueva ficha se debe especificar el área al cual corresponde esa ficha.
5-	Todas las fichas debe tener un personal de la salud asociado. 
6-	Cada consulta debe tener un paciente asociado.
7-	El personal de la salud solo podrá editar fichas que correspondan a su área, como así también las consultas hechas por el paciente.
8-	Los datos personales de los pacientes pueden ser modificados.
9-	Los datos de las consultas pueden ser modificados.
10-	Una ficha puede ser eliminada, pero solo debe ser un borrado ocioso.
11-	Las consultas deben ser actualizadas en caso de existir algún análisis, nuevo diagnóstico o tratamiento del paciente.

**Comment by KariSanabria** [comment]
# Políticas de las Fichas

## Crear Fichas

1-  Las fichas pueden ser creadas por el personal de la salud o cualquier otro empleado cuyo rol permita realizar dicha tarea Ej: la secretaria
2-  Cada paciente debe tener una ficha una vez hecha la consulta.
3-  El paciente no debe tener más de una ficha del mismo tipo. 
4-  Para crear una nueva ficha se debe especificar el área al cual corresponde esa ficha.
5-  Todas las fichas debe tener un personal de la salud asociado. 
6-  Cada consulta debe tener un paciente asociado.
7-  El personal de la salud solo podrá editar fichas que correspondan a su área, como así también las consultas hechas por el paciente.
8-  Los datos personales de los pacientes pueden ser modificados.
9-  Los datos de las consultas pueden ser modificados.
10- Una ficha puede ser eliminada, pero solo debe ser un borrado ocioso.
11- Las consultas deben ser actualizadas en caso de existir algún análisis, nuevo diagnóstico o tratamiento del paciente.

**Comment by rofaccess** [comment]
Mi opinión:
En el 5 y 6, Creo que la consulta es la que debe tener un profesional de la salud asociado y no la ficha, porque las consultas podrían ser atendidas por más de un profesional. Y las consultas deberian estar relacionadas con la ficha, sería como que las consultas son detalles de cierta ficha, y en cada consulta se podría actualizar valores variables de la ficha por ejemplo: peso, altura, etc.

Para el 11, creo que en vez de actualizar la consulta, se debería crear una nueva consulta donde se registren los nuevos datos variables, porque habría que registrar la fecha en que se da el nuevo diagnóstico por ejemplo. Aún así darle la flexibilidad de poder editar una consulta no esta mal, y en ese caso basta decir que las consultas pueden ser editadas por alguien con los permisos necesarios o algo asi.

El resto, creo que esta bien.

**Comment by Lesfig** [comment]
Opino exactamente igual que Rodrigo, la ficha debe estar asociada al área nomas, cada consulta debe estar asociada al profesional, y relacionada con una ficha. Cada vez que el paciente realiza una consulta se crea una nueva, sea por el motivo que fuese  :)

**Comment by KariSanabria** [comment]
# Políticas de las Fichas

## Crear Fichas

1-  Las fichas pueden ser creadas por el personal de la salud o cualquier otro empleado cuyo rol permita realizar dicha tarea Ej: la secretaria
2-  Cada paciente debe tener una ficha una vez hecha la consulta.
3-  El paciente no debe tener más de una ficha del mismo tipo. 
4-  Para crear una nueva ficha se debe especificar el área al cual corresponde esa ficha.
5-  Las consultas debe tener un personal de la salud asociado. 
6-  Cada consulta debe tener una ficha asociada.
7-  El personal de la salud solo podrá editar fichas que correspondan a su área, como así también las consultas hechas por el paciente.
8-  Los datos personales de los pacientes pueden ser modificados.
9-  Los datos de las consultas pueden ser modificados.
10- Una ficha puede ser eliminada, pero solo debe ser un borrado ocioso.
11- Se debe crear nuevas consultas en caso de existir algún nuevo análisis, diagnóstico o tratamiento del paciente.

**Comment by KariSanabria** [comment]
@rofaccess @Lesfig realizados los cambios sugeridos.

**Comment by rofaccess** [comment]
Tendremos 2 formas de registrar fichas:
1. En un abm de fichas, esto es más para carga inicial, si es que quieren registrar las fichas que ya tienen en papeles.
2. Durante la asignación de turno se generará automáticamente si el paciente no lo tiene en el área a consultar.

Entonces para:
2- Cada paciente debe tener una ficha una vez hecha la consulta.
Lo mejor sería que la ficha ya exista antes de una consulta y tendría los datos de identificación del paciente.

Faltaría aclarar que pasa si se borra una ficha, ¿Se borran también las consultas asociadas?, y a nivel de base datos si hay alguna relación ON DELETE CASCADE o RESTRICT entre ficha y consulta, esto es más por un buen diseño de la base de datos, ya que no esperamos que se lo modifique directamente.

El resto creo que esta bien.

**Comment by KariSanabria** [comment]
# Políticas de las Fichas

# Crear Fichas
1. Las fichas pueden ser creadas por el personal de la salud o cualquier otro empleado cuyo rol permita realizar dicha tarea Ej: la secretaria
2. Se tendrá un abm de fichas para la carga inicial en caso de que quieran registrar las fichas(papeles) ya existentes.
3. Durante la asignación de turno se generará automáticamente una ficha si el paciente no lo tiene en el área a consultar.
4. Una vez eliminada la ficha de un paciente, se elimina la consulta asociada a la misma.
5. El paciente no debe tener más de una ficha del mismo tipo. 
6. Para crear una nueva ficha se debe especificar el área al cual corresponde esa ficha.
7. Las consultas debe tener un personal de la salud asociado. 
8. Cada consulta debe tener una ficha asociada.
9. El personal de la salud solo podrá editar fichas que correspondan a su área, como así también las consultas hechas por el paciente.
10. Los datos personales de los pacientes pueden ser modificados.
11. Los datos de las consultas pueden ser modificados.
12. Una ficha puede ser eliminada así como las consultas relacionadas a la misma, pero solo debe ser un borrado ocioso.
13. Se debe crear nuevas consultas en caso de existir algún nuevo análisis, diagnóstico o tratamiento del paciente.
14. A nivel de base de datos la relación entre la ficha y la consulta tendrá una restricción de ON DELETE CASCADE.

**Comment by rofaccess** [comment]
Kari. Te doy el visto bueno para que cierres (Je je).

**Comment by KariSanabria** [comment]
OK.
