### ISSUE TITLE
Definir la documentación para el feature Turno

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#22]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by rofaccess** [comment]
# Feature Turnos

## Descripción

En esta sección se puede asignar un turno a un paciente, en el área que desea consultar, también se puede cancelar el turno o pasarlo a otra fecha.
Se ingresa a la interfaz de Turnos a través del menú Turnos

## Asignar Turno

### Flujo Principal
1. En la interfaz de Turnos, se muestra por defecto el formulario de nuevo turno.
2. Se deberá especificar el área a consultar y la fecha.
3. El sistema mostrará los profesionales de Salud disponibles, el costo por área y por profesional.
4. Se podrá seleccionar con cuales de los profesionales va a consultar el paciente
5. Se tendrá un campo de búsqueda, donde se especificará el ci, nombre y/o apellido del paciente para buscarlo en el sistema.
6. Se especifica los datos del paciente y se ejecuta la búsqueda.
7. Si el paciente ya se encuentra en el sistema, se mostraŕan sus datos básicos.
   7.1. Si el paciente no se encuentra en el sistema, se mostrará un mensaje: “El paciente no está     registrado” y se especifica otro dato del paciente (Pasar a 6)  .
   7.1. Si el paciente no se encuentra en el sistema, se mostrará un mensaje: “El paciente no está     registrado” y se procede a registrar el paciente (Pasar a Flujo de Registrar Paciente) 
8. Se especifica si el paciente pagará o no por la consulta a través de un checkbox
9. Si el paciente paga se deberá registrar el monto y el número de factura a emitir.
   9.1. Si el paciente no paga se le exonera el costo.
10. Se clickea en el botón “Guardar”
11. En el controlador, se verifica si el paciente tiene una ficha en el área especificada. Si no tiene ficha se lo genera automáticamente.
12. Al guardar el turno, si no hubo ningún problema, se redirecciona a una pantalla que muestra el turno recien guardado y se muestra el mensaje: “Al paciente nombre_apellido  se le ha asignado un turno” (Fin).
    12.1. Al guardar el turno, si hubo algún problema, se redirecciona a la pantalla de asignar turno  y se muestra el mensaje:  “No se ha podido guardar el turno”, si es posible, el mensaje deberá     especificar el motivo (Pasar a 2).

## Registrar Paciente

### Flujo Principal
1. En la interfaz de  nuevo turno, se tiene la opción de registrar al paciente, si es que no está previamente registrado
2. Se clickea sobre el botón “Agregar Paciente”, que despliega un formulario para registrar los datos básicos del paciente. Los campos del formulario están validados. El formulario desplegado se puede cerrar en cualquier momento.
3. Si el paciente es menor, a través de un checkbox se muestra o no los datos específicos para el menor, como ser quienes son sus padres o encargados.
4. Se clickea en la opción “Guardar”.
5. Al guardar el paciente, si no hubo ningún problema, se cierra el formulario, se muestran los datos básicos del paciente en la interfaz de nuevo turno y se muestra el mensaje: “El paciente nombre_apellido ha sido guardado” (Pasar al punto 8 de Asignar Turno).
   5.1. Al guardar el paciente, si hubo algún problema, se sigue mostrando a la pantalla de agregar paciente y se muestra el mensaje:  “No se ha podido guardar el paciente nombre_apellido”, si es posible, el mensaje deberá especificar el motivo (Pasar a 3).
   (Nota: Se sigue mostrando el formulario, para que no pierdan los datos que ya estaban   especificados, esto para evitar tener que escribirlos de vuelta, si el error fue a causa de algún  campo llenado de forma incorrecta).

## Mostrar Turno

### Descripción
1. En la interfaz de listar turnos, por cada registro se tiene la opción ver, que mostrará el turno y tendrá la opción para cancelarlo, o pasarlo a otra fecha.
2. La opción cancelar solo setea el estado del turno a cancelado.
3. En la pantalla de ver turno se tiene la opción de nuevo turno y listar turnos.

## Listar Turno

### Descripción
1. En la interfaz de nuevo turno, se tiene una opción para acceder a la lista de turnos, cada registro muestra cierto campos concernietes al turno,.
2. Sobre el listado se tiene un campo de busqueda, para buscar sobre cualquier campo de la lista. También se tiene un botón de “Busqueda Avanzada” que desplegará más campos, para filtrar los datos de la lista, de una manera más específica.
3. En esta pantalla se tienen las opciones: “Nuevo turno” (Permite agregar un nuevo turno), “Ver”, “Editar”, “Eliminar”, por cada registro de la lista.
4. La lista tiene paginación.

## Dependencias

Ninguna 

## Gemas necesarias
1. Ransack 1.7.0
2. Kaminari 0-17
3. jQuery Validation Plugin – v1.15.0
4. Input Mask plugin for jquery – v0.0.0

## Prioridad

10

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 01h00m

**Comment by rofaccess** [comment]
Esto ya lo había terminado ayer, Me olvidé de pasar a Ready to Test.

Espero comentarios y Sugerencias.

**Comment by Lesfig** [comment]
Creo que el punto 3 de asignar turnos está demás.. 
Y también pienso que sería lindo un menú lateral con las áreas como opciones y que se escoja de ahí el área para sacar turno

**Comment by rofaccess** [comment]
Asignar turno, es la interfaz donde se le asigna turno a un paciente, se le puede renombrar a nuevo turno.
En el menú lateral se podría mostrar un calendario como este:
![screenshot from 2016-04-02 00-38-53](https://cloud.githubusercontent.com/assets/2489653/14224487/53b9c680-f86c-11e5-91ba-73047753bfc7.png)

Alli se selecciona una fecha y automáticamente debajo se listan las áreas que tienen disponibilidad en esa fecha y su costo de área.

Al seleccionar un área, justo debajo de la lista de areas te muestra la lista de los profesionales con cupos disponibles con su costo de profesional.

Al selecionar el profesional, se asume que se va a consultar con ese profesional, entonces en el formulario de nuevo turno solo se seteará el paciente, el monto que paga, y el numero de factura. 

Si se hace de esta manera va a sobrar mucho espacio, así que se podría mostrar todos los datos del paciente. Y si el paciente no esta registrado, se puede cargar ahi mismo el dato del paciente sin necesidad de desplegar un modal, como se tenía previsto en Registrar Paciente.

**Comment by bordonwork** [comment]
@rofaccess todo correcto
