### ISSUE TITLE
Definir la documentación para el feature Atención Profesional

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#23]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by KariSanabria** [comment]
# Feature Atención Profesional

## Descripción

Éste feature tiene como fin facilitar el proceso de atención al profesional de la salud. Podrá listar los pacientes a atender, ver la ficha del paciente, mostrar su historial médico y registrar nueva consulta.

## Agregar  Consulta

### Flujo Principal
1. En la interfaz de Consulta, se podrá visualizar la ficha del primer paciente a atender.
2. En esta ficha se tendrá en la parte inferior la opción para “Crear Consulta”.
3. En esta opción se registra todos los datos necesarios e importantes para la primera consulta, los datos varían según el área de consulta.
4. Se podrá agregar datos variables en la consulta, en caso de que el paciente asista cierto tiempo después por otros motivos.
5. También se tiene la opción de controles
6. En esta opción se podrá “Agregar un nuevo Control” cada vez que el paciente asista para un chequeo del tratamiento que sigue.

## Mostrar Ficha/Consultas

### Descripción
1. En la interfaz de Consulta, se podrá visualizar la ficha del primer paciente a atender.
2. En el lado izquierdo de la interfaz se muestra un menú lateral, en la misma se encuentra la lista de los nombres de los pacientes a atender ese día.
3. Además de un calendario donde se podrá elegir una fecha pasada para ver los pacientes atendidos anteriormente y,
4. Seleccionar una fecha futura, si no existe pacientes a atender se muestra un mensaje “No hay pacientes”.
5. Se podrá ver la actividad actual, como ver cantidad de pacientes ya atendidos y los pendientes.
6. En la ficha del paciente se puede visualizar todos los datos personales del paciente, y  en la parte inferior se podrá ver las consultas hechas por la misma anteriormente.

## Editar Ficha/Consulta

### Flujo Principal
1. En la interfaz de Consulta, se podrá visualizar la ficha del primer paciente a atender.
2. En la parte inferior, en la opción consulta se tiene un botón “Editar”.
3. Así también en la opción de Control se tiene un botón “Editar” para poder modificar los datos necesarios.
4. Se tendrá en cuenta siempre las restricciones de validación. Se edita los datos.
5. Se clickea en el botón “Guardar” del formulario.
6. Al guardar  la ficha o consulta, si no hubo ningún problema, se muestra el mensaje: “La ficha del paciente  nombre_paciente ha sido actualizado” o “La consulta del paciente ha sido actualizado”.
7. Al guardar la ficha o consulta, si hubo algún problema, se muestra el mensaje: “No se ha podido actualizar el paciente nombre_paciente”, si es posible, el mensaje deberá especificar el motivo.

## Dependencias
1. ABM Fichas

## Gemas necesarias
1. jQuery Validation Plugin – v1.15.0

## Prioridad

10

**Tiempo Utilizado:** 01h:00m
