### ISSUE TITLE
Definir la documentación para el feature Fichas

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#24]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by Lesfig** [comment]
# Feature Fichas:

## Descripción

En el feature fichas, el profesional de la salud podrá registrar los datos necesarios e importantes del paciente, así también las consultas realizadas, para poder tener un seguimiento de las consultas. Estas también se podrán editar por el mismo.

## Agregar Fichas y Consultas

### Flujo Principal

1- En el menú(layout) habrá una opción pacientes y consultas, y la opción fichas como uno de los submenús, al dar click en ella se mostrará en el lado izquierdo un menú lateral con todas las fichas distintas disponibles como opción, y se mostrará por defecto la lista de todas las fichas emitidas por la primera opción del menú lateral.  En la parte superior derecha de la interfaz, se tiene el botón “Agregar Ficha”.

2- Al clickear en el botón “Agregar Ficha” se muestra el formulario de “Nueva ficha”.

3- En el formulario se tiene los inputs de la ficha correspondiente a ser rellenados. 

4- El c.i. del paciente, antes de guardar, se debe validar si ya existe o no, un paciente con una ficha con el mismo ci, si no existe se guardan los datos (**Nota:** Se guardan los datos siempre y cuando los otros datos se también cumplan con las condiciones).

5- En la parte inferior derecha habrá un botón para “guardar ficha”, también un botón "agregar nueva consulta".

6- Al dar click en guardar ficha, se guardarán los datos de las fichas y se mostrará un mensaje de éxito al guardar,  al clickear en el botón "agregar nueva consulta", se redirigirá a la interfaz de Agregar consulta, en la parte superior se mostrará algunos datos del paciente, en el medio los campos de nueva consulta a ser rellenados, y en la parte inferior la lista de todas las consultas realizadas por el paciente en el área.

7- Al dar click en "guardar consulta" se listará automáticamente la consulta en la lista nombrada en el punto anterior.

8- También en la opción pacientes y consultas del menú(layout), habrá una opción consultas como uno de los submenús, al dar click en ella se mostrará una lista de todos los pacientes con sus respectivas fichas y con la opción agregar nueva consulta como opción, al dar click en ella redirigirá a la interfaz agregar consulta nombrada en el punto 6

### Flujo Alternativo

4.1. Si el paciente ya  tiene una ficha en el área deseada, se muestra el mensaje: “El paciente ya tiene una ficha”.

4.2 Al guardar ficha, si hubo algún problema, se redirecciona a la pantalla de agregar ficha y se muestra el mensaje: “No se ha podido guardar los datos”, si es posible, el mensaje deberá especificar el motivo.

## Editar Ficha

### 

Flujo Principal

1-En la interfaz de Fichas, se muestra por defecto una tabla con la lista de fichas, cada registro de la tabla tiene un botón para editarlo.

2-Al clickear en el botón “Editar” se muestra el formulario de “Editar Ficha”.

3-En el formulario se muestran datos de los campos con los datos del paciente, el paciente podrá editar cualquiera de ellos.

4- El c.i. del paciente, antes de guardar, se debe validar si ya existe o no, un paciente con una ficha con el mismo ci, si no existe se guardan los datos (Nota: Se guardan los datos siempre y cuando los otros datos se también cumplan con las condiciones).

5- Se clickea en el botón “Guardar Cambios” del formulario.

6-Al guardar la ficha, si no hubo ningún problema, se redirecciona a una pantalla que muestra la ficha editada y se muestra el mensaje de éxito.

### Flujo Alternativo

4.1 Al guardar ficha, si hubo algún problema, se redirecciona a la pantalla de agregar ficha y se muestra el mensaje: “No se ha podido guardar los datos”, si es posible, el mensaje deberá especificar el motivo.

## Dependencias

ABM de Pacientes
Consultas depende de ABM Fichas

## Gemas necesarias

0-  Ransack 1.7.0
1-  Kaminari 0-17

## Prioridad

10

**Comment by bordonwork** [comment]
@Lesfig falta la lista de vistas. Las necesito para cargar las tareas de diseño de interfaces

**Comment by Lesfig** [comment]
# Feature Fichas:

## Descripción

En el feature fichas, el profesional de la salud podrá registrar los datos necesarios e importantes del paciente, así también las consultas realizadas, para poder tener un seguimiento de las consultas. Estas también se podrán editar y ver por el mismo.

Hay 10 fichas distintas, cada una posee vista para agregar Ficha, dentro de la misma podrá agregar Consultas y dentro de consultas sus distintos controles, las fichas son las siguientes:

-Ficha Psicopedagogía
-Ficha  Fisioterapia Adulto
-Ficha Pediatría 
-Ficha Neurología 
-Ficha Clínico
-Ficha Nutricional Adulto
 -Ficha Nutricional Pediatrica 
-Ficha Fonoaudiología
-Ficha Odontológia
-Ficha psicopedagogía2

## Agregar Fichas y Consultas(y Controles)

## Flujo Principal

1- En el menú(layout) habrá una opción pacientes y consultas, y la opción fichas como uno de los submenús, al dar click en ella se mostrará en el lado izquierdo un menú lateral con todas las fichas distintas disponibles como opción, y se mostrará por defecto la lista de todas las fichas emitidas por la primera opción del menú lateral con las opción "ir a ficha". En la parte superior izquierda de la interfaz, se tiene el botón “Agregar Ficha”.

2- Al clickear en el botón “Agregar Ficha” se muestra el formulario de “Nueva ficha” según el área escogida en el punto1.

3- En el formulario se tiene los campos de la ficha correspondiente a ser rellenados, cada ficha se dividirá en dos partes ficha y consultas, cada consulta tendrá sus controles, Todo se mostrará en una interfaz en la parte superior se mostrará los campos "fijos de la ficha" si hay grandes divisiones de datos se mostrará en tabs para evitar que la ficha sea muy grande.

4- En el medio de la ficha se tendrá las consultas también en forma de tabs, si el profesional quiere agregar una nueva consulta solo bastará en dar click en el siguiente tab que tendrá como título el signo "+", cuando le aprieta "guardar" se listará la consulta en el tab, dentro de consultas se tendrá nuevamente tabs pero para los controles que se manejará al igual que consulta.

5- Antes de guardar, se debe validar si el paciente ya tiene o no una ficha, si no tiene se guardan los datos (Nota: Se guardan los datos siempre y cuando los otros datos se también cumplan con las condiciones).
      5.1. Si el paciente ya tiene una ficha en el área deseada, se muestra el mensaje: “El paciente ya tiene una ficha”.

```
  5.2 Al guardar ficha, si hubo algún problema, se redirecciona a la pantalla de agregar ficha y se muestra el mensaje: “No se ha podido guardar los datos”, si es posible, el mensaje deberá especificar el motivo.
```

6- En la parte inferior derecha habrá un botón para “guardar ”.

7- Al dar click en guardar ficha, se guardarán los datos de las fichas y se mostrará un mensaje de éxito al guardar, en la interfaz agregar ficha.

## Editar Ficha

## Flujo Principal

1-En Fichas, se muestra por defecto una tabla con la lista de fichas (punto1 agregar fichas), cada registro de la tabla tiene una opción para ir a ficha, las consultas y controles ya hechos tendrán un botón editar.  

2-Al clickear en  “Editar” de consultas y controles,se muestra la porción de consultas o controles, con los campos en forma editable

4- Se guardan los datos siempre y cuando sean validos.

```
4.1 Al guardar ficha, si hubo algún problema, se redirecciona a la pantalla de editar ficha y se muestra el mensaje: “No se ha podido guardar los datos”, si es posible, el mensaje deberá especificar el motivo.
```

5- Se clickea en el botón “Guardar Cambios” del formulario.

6-Al guardar la ficha, si no hubo ningún problema, te muestra la misma interfaz pero con ficha editada y se muestra el mensaje de éxito.

## Dependencias

ABM de Pacientes

## Gemas necesarias

0- Ransack 1.7.0
1- Kaminari 0-17
2-Cocoon 1.2.7 

## Prioridad

10

**Comment by Lesfig** [comment]
@KariSanabria , @rofaccess @bordonwork

**Comment by Lesfig** [comment]
@KariSanabria y @rofaccess

**Comment by Lesfig** [comment]
tiempo utilizado con las modificaciones 07h:00m

**Comment by bordonwork** [comment]
@Lesfig veo todo correcto, perdón por la demora, problemas de internet
