### ISSUE TITLE
Definir la documentación para el feature Horarios de Atención

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#25]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by KariSanabria** [comment]
# Feature de Horarios de Atención

## Descripción

En éste feature se puede agregar, editar, listar, eliminar e incuso imprimir los  horarios de atención de todo el personal de la salud. Cualquier usuario con los permisos correspondientes puede acceder a esta sección.
Se podrá acceder a la interfaz a través del submenú horario de atención del menú Personal. 

## Flujo Principal
1. En la interfaz de horarios se muestra por defecto una lista de todo el personal de la salud .En la parte superior derecha se tendrá  la opción de búsqueda, para buscar sobre cualquier campo de la lista. 
2. Cada uno de estos registros tendrá la opción de ver, editar y eliminar.
3. Al hacer click en la opción **ver** despliega un formulario donde está especificado todos los horarios de atención del personal de la salud seleccionada.
4. En la parte superior derecha de la interfaz, se tiene el botón “Agregar Horario”.
5. En este formulario se especifican los datos del personal de la salud, a medida que se van cargando los datos, los mismos ya se van validando.
6. También en este formulario se debe agregar las fechas, hora y los meses disponibles para la atención.
7. Se clickea en el botón “Guardar” del formulario.
8. Al guardar el horario, si no hubo ningún problema se muestra el mensaje: “El horario de nombre_del_personal ha sido guardado”.
9. **Para editar**, seleccionar la opción editar que tiene cada uno de los registros de la lista del personal de la salud.
10. Se muestra los datos necesarios del personal de la salud y sus horarios de atención como las fechas, horas y meses.
11. Las restricciones de validación serán las mismas que “Agregar nuevo horario ", se podrá editar todo el horario de dicho personal de la salud seleccionada.
12. Realizado los cambios necesarios se clickea el botón guardar y se guardan los cambios
13. Si al guardar no hubo ningún problema se muestra el mensaje “Se ha actualizado el horario de nombre_del_personal ”
14. **Para eliminar**, por defecto en la lista de empleados, cada registro de la tabla tiene un icono para eliminarlo.
15. Al clickear en el botón “Eliminar” se muestra un mensaje de confirmación: “¿Desea eliminar el horario de nombre_del_personal?” con las opciones “Si” “No”.
16. Se podrá imprimir la lista de horarios de atención de cada personal de la salud que se desee.

## Gemas necesarias
1. Ransack 1.7.0
2. Kaminari 0-17

## Prioridad: Alta

**Comment by KariSanabria** [comment]
Ésta es la primera versión de lo que seria el feature, no esta completa, de hecho el flujo principal es de forma generalizada,puede variar. Estaría alzando el documento completa, mas detallado después de finiquitar algunos puntos importantes.

**Comment by KariSanabria** [comment]
# Feature Horarios de Atención

## Descripción

En éste Feature se puede agregar, editar, listar, ver, eliminar e imprimir los horarios de atención de todo el personal de la salud. Cualquier usuario con los permisos correspondientes puede acceder a esta sección.
Se podrá acceder a la interfaz a través del submenú horario de atención del menú Personal.

## Agregar Horarios de Atención

### Flujo Principal
1. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios.
2.  En el lado izquierdo de la interfaz se muestra un menú lateral, en la misma se encuentra la opción “Lista de Horarios de Atención” especificada, en la parte superior se tiene el botón “Crear Horario”.
3. Al clickear en el botón “Crear Horario” se muestra el formulario de “Nuevo Horario”.
4. En el formulario se tiene un input de búsqueda, que permite buscar a un profesional de la salud.
5. Se ingresa el nombre del profesional y el buscador ira mostrando coincidencias.
6. Si el profesional de la salud existe, se muestran sus datos básicos, como nombres y apellidos, C.I, su área correspondiente y se especifica el año actual al que corresponderá ese horario de atención.
7. En el formulario se tiene para seleccionar los meses y los días que atenderá el profesional de la salud y la opción de marcar todos para facilitar la selección.
8. Tiene la opción para indicar si la atención será turno mañana o turno tarde y especificar la hora inicio y hora fin, además tendrá una opción por defecto para setear la hora inicio y hora fin en base a una tabla que contendrá la hora preestablecida.
9. En caso de que la atención no sea todos los días se tiene la opción para especificar cada cuanta semana será la misma y la fecha inicio y fecha fin.
10. Cada uno de estos datos se reflejaran en un calendario para una mejor visualización.
11. Al poner el puntero sobre una fecha específica te muestra en un mensaje la hora inicio y fin por turno.
12. Con un click se colorea y descolorea las fechas del calendario, que habilita y deshabilita las fechas.
13. Una vez cargado el formulario se hace click en el botón “Guardar” del formulario.
14. Al guardar el horario, si no hubo ningún problema, se muestra el mensaje: “El horario de nombre_profesional ha sido guardado”,
15. Caso contrario, si hubo algún problema, se muestra el mensaje: “No se ha podido guardar el horario de nombre_profesional”, si es posible, el mensaje deberá especificar el motivo.

## Editar Horarios de Atención

### Flujo Principal
1. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para editarlo.
2. Al clickear en el botón “Editar” se muestra el formulario de “Editar horario”.
3. Se modifica los datos necesarios y se actualizan. Las restricciones de validación son las mismas que en “Nuevo Horario”.
4. Se clickea en el botón “Guardar” del formulario.
5. Al guardar el horario, si no hubo ningún problema, se muestra el mensaje: “El horario de nombre_profesional ha sido actualizada”,
6. Caso contrario, si hubo algún problema, se muestra el mensaje: “No se ha podido actualizar el horario de nombre_profesional”, si es posible, el mensaje deberá especificar el motivo.

## Eliminar Horarios de Atención

### Flujo Principal
1. En la interfaz de horario, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para eliminarlo.
2. Al clickear en el botón “Eliminar” se muestra un mensaje de confirmación: “¿Desea eliminar el horario de nombre_profesional?” con las opciones “Si” “No”.
3. La opción “No” cancela el borrado. La opción “Si” borra el horario, muestra la lista de horario de atención, y muestra el mensaje “El empleado nombre_profesional ha sido eliminado”. Este borrado será un borrado ocioso.
   ## Mostrar Horarios de Atención
   ### Descripción
4. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para ver el horario de atención de dicho personal.
5. Al clickear en el botón “Ver” se muestra todos los horarios de atención del profesional de la salud de un año.
6. Estos horarios se muestran en calendarios, marcadas todas las fechas de atención.
7. En la parte inferior izquierdo de este formulario se tiene los botones  con las opciones “Eliminar” (Permite eliminar el paciente), “Editar” (Muestra el formulario de edición para modificar).
   ## Listar Horarios de Atención
   ### Descripción
8. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para “Ver” (Muestra el horario de atención de un año), “Eliminar” (Permite eliminar el horario), “Editar” (Muestra el formulario de edición).
9. En el listado se tiene un campo de búsqueda, para buscar sobre cualquier campo de la lista.
10. También se tiene una opción de “Búsqueda Avanzada”.
11. Al clickear sobre el icono de búsqueda, esta despliega algunos campos, para realizar alguna búsqueda más específica.
12. Se clickea en el botón “Filtrar”.
13. Se puede imprimir la lista de horarios.

La lista tiene paginación.

## Dependencias

ABM Empleados

## Gemas necesarias
1. Select2 plugin
2. Ransack 1.7.0
3. Kaminari 0-17

## Prioridad

10

**Tiempo Utilizado:** 2h30m

**Comment by rofaccess** [comment]
Como se trata de un abm de horarios. creo que seria mas correcto decir que se tiene una lista de horarios, y no de personal o empleado.
con lo demas no hay drama.

**Comment by KariSanabria** [comment]
# Feature Horarios de Atención

## Descripción

En éste Feature se puede agregar, editar, listar, ver, eliminar e imprimir los horarios de atención de todo el personal de la salud. Cualquier usuario con los permisos correspondientes puede acceder a esta sección.
Se podrá acceder a la interfaz a través del submenú horario de atención del menú Personal.

## Agregar Horarios de Atención

### Flujo Principal
1. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios.
2.  En el lado izquierdo de la interfaz se muestra un menú lateral, en la misma se encuentra la opción “Lista de Horarios de Atención” especificada, en la parte superior se tiene el botón “Crear Horario”.
3. Al clickear en el botón “Crear Horario” se muestra el formulario de “Nuevo Horario”.
4. En el formulario se tiene un input de búsqueda, que permite buscar a un profesional de la salud.
5. Se ingresa el nombre del profesional y el buscador ira mostrando coincidencias.
6. Si el profesional de la salud existe, se muestran sus datos básicos, como nombres y apellidos, C.I, su área correspondiente y se especifica el año actual al que corresponderá ese horario de atención.
7. En el formulario se tiene para seleccionar los meses y los días que atenderá el profesional de la salud y la opción de marcar todos para facilitar la selección.
8. Tiene la opción para indicar si la atención será turno mañana o turno tarde y especificar la hora inicio y hora fin, además tendrá una opción por defecto para setear la hora inicio y hora fin en base a una tabla que contendrá la hora preestablecida.
9. En caso de que la atención no sea todos los días se tiene la opción para especificar cada cuanta semana será la misma y la fecha inicio y fecha fin.
10. Cada uno de estos datos se reflejaran en un calendario para una mejor visualización.
11. Al poner el puntero sobre una fecha específica te muestra en un mensaje la hora inicio y fin por turno.
12. Con un click se colorea y descolorea las fechas del calendario, que habilita y deshabilita las fechas.
13. Una vez cargado el formulario se hace click en el botón “Guardar” del formulario.
14. Al guardar el horario, si no hubo ningún problema, se muestra el mensaje: “El horario de nombre_profesional ha sido guardado”,
15. Caso contrario, si hubo algún problema, se muestra el mensaje: “No se ha podido guardar el horario de nombre_profesional”, si es posible, el mensaje deberá especificar el motivo.

## Editar Horarios de Atención

### Flujo Principal
1. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para editarlo.
2. Al clickear en el botón “Editar” se muestra el formulario de “Editar horario”.
3. Se modifica los datos necesarios y se actualizan. Las restricciones de validación son las mismas que en “Nuevo Horario”.
4. Se clickea en el botón “Guardar” del formulario.
5. Al guardar el horario, si no hubo ningún problema, se muestra el mensaje: “El horario de nombre_profesional ha sido actualizada”,
6. Caso contrario, si hubo algún problema, se muestra el mensaje: “No se ha podido actualizar el horario de nombre_profesional”, si es posible, el mensaje deberá especificar el motivo.

## Eliminar Horarios de Atención

### Flujo Principal
1. En la interfaz de horario, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para eliminarlo.
2. Al clickear en el botón “Eliminar” se muestra un mensaje de confirmación: “¿Desea eliminar el horario de nombre_profesional?” con las opciones “Si” “No”.
3. La opción “No” cancela el borrado. La opción “Si” borra el horario, muestra la lista de horario de atención, y muestra el mensaje “El empleado nombre_profesional ha sido eliminado”. Este borrado será un borrado ocioso

.

## Mostrar Horarios de Atención

### Descripción
1. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para ver el horario de atención de dicho personal.
2. Al clickear en el botón “Ver” se muestra todos los horarios de atención del profesional de la salud de un año.
3. Estos horarios se muestran en calendarios, marcadas todas las fechas de atención.
4. En la parte inferior izquierdo de este formulario se tiene los botones  con las opciones “Eliminar” (Permite eliminar el paciente), “Editar” (Muestra el formulario de edición para modificar).

## Listar Horarios de Atención

### Descripción
1. En la interfaz de horario de atención, se muestra por defecto una tabla con la lista de horarios, cada registro de la tabla tiene un botón para “Ver” (Muestra el horario de atención de un año), “Eliminar” (Permite eliminar el horario), “Editar” (Muestra el formulario de edición).
2. En el listado se tiene un campo de búsqueda, para buscar sobre cualquier campo de la lista.
3. También se tiene una opción de “Búsqueda Avanzada”.
4. Al clickear sobre el icono de búsqueda, esta despliega algunos campos, para realizar alguna búsqueda más específica.
5. Se clickea en el botón “Filtrar”.
6. Se puede imprimir la lista de horarios.
7. La lista tiene paginación.

## Dependencias

ABM Empleados

## Gemas necesarias
1. Select2 plugin
2. Ransack 1.7.0
3. Kaminari 0-17

## Prioridad

10

**Tiempo Utilizado:** 2h:30m

**Comment by KariSanabria** [comment]
@rofaccess @Lesfig realizado los cambios, espero confirmación para cerrrar :)

**Comment by Lesfig** [comment]
bueno, en el punto uno.. pienso que debe entrar directo en crear horario.. y en el costado izquierdo un menú lateral con los distintos profesionales en forma de lista, con sus especialidades(como hicimos en las interfaces), si da click en uno de ellos que te muestre su horario y abajo tendrá las opciones elinimar y editar(como la interfaz de usuario).. Y después todo ok
