### ISSUE TITLE
Definir la documentación para el feature Reporte Estadístico

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#26]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by rofaccess** [comment]
# Feature Reporte Estadístico:

## Descripción

En esta sección se puede generar un reporte estadístico por área de especialidad ya sea por mes o por año, el reporte especifica la cantidad de pacientes atendidos por área.
Se ingresa a la interfaz de Reporte Estadístico, a través del menú Reporte

## Generar Reporte Estadístico

### Descripción
1. En la interfaz de Reporte Estadístico, se muestra por defecto el reporte correspondiente al mes actual. Básicamente es una lista de todas las áreas y cuántos pacientes se atendió en total por cada área.
2. Se puede especificar a través de un select si se quiere un reporte por mes o por año.
3. Se puede especificar a través de un select si se quiere un reporte por doctor o por área. Tambien se puede especificar un doctor especifico y/o un area especifica.
   (Nota:  Este punto no es un requerimento específico, se lo incluye para dar más posibilidades )
4. Por cada fila del reporte también se especifica el límite de pacientes que en teoría se debió atender.
5. El botón “Generar Reporte”, actualiza el reporte
6. Se tiene la opción para imprimir el reporte generado.

## Dependencias

Ninguna 

## Gemas necesarias

Ninguna.

## Prioridad

3

(Obs.: En una búsqueda rápida encontré esto https://developers.google.com/chart/ para mostrar gráficos estadísticos con javascript, parece fácil mostrarlo en la interfaz, pero imprimirlo no lo sé, lo menciono, para tenerlo en cuenta por ahí si nos sobra tiempo.)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 00h30m

**Comment by Lesfig** [comment]
Creo que también debe haber un filtro por si quiere sólo de un doctor el reporte, o sólo de un área. Y no sé si se verá lindo los radios buttons.. bueno, eso es cuestión de ver en el diseño de la interfaz

**Comment by rofaccess** [comment]
Modifique segun las sugerencias.
