### ISSUE TITLE
Definir la documentación para el feature Empleados

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#27]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by rofaccess** [comment]
# Feature Empleados:

## Descripción

En esta sección se puede agregar, modificar y eliminar empleados. Cualquier usuario con los permisos correpondientes puede acceder a esta sección.
Se ingresa a la interfaz de empleados, a través del submenu empleados del menú Personal.

## Agregar Empleado

### Flujo Principal
1. En la interfaz de empleados, se muestra por defecto una tabla con la lista de empleados. En la parte superior derecha de la interfaz, se tiene el botón “Agregar Empleado”.
2. Al clickear en el botón “Agregar Empleado” se muestra el formulario de “Nuevo Empleado”.
3. Se especifican los datos del empleado, a medida que se van cargando los datos, los mismos ya se van validando, si es que hay alguna restricción que cumplir. Algunos campos aceptan sólo números, otros son obligatorios.
4. Se clickea en el botón “Guardar” del formulario.
5. Al guardar el empleado, si no hubo ningún problema, se redirecciona a una pantalla que muestra el empleado recien guardado y se muestra el mensaje: “El empleado nombre_apellido ha sido guardado” (Fin).
   5.1. Al guardar el empleado, si hubo algún problema, se redirecciona a la pantalla de agregar empleado y se muestra el mensaje:  “No se ha podido guardar el empleado nombre_apellido”, si es posible, el mensaje deberá especificar el motivo (Pasar a 3).

## Editar Empleado

### Flujo Principal
1. En la interfaz de empleados, se muestra por defecto una tabla con la lista de empleados, cada registro de la tabla tiene un botón para editarlo.
2. Al clickear en el botón “Editar” se muestra el formulario de “Editar Empleado”.
3. Se actualizan los datos. Las restricciones de validación son las mismas que en “Nuevo Empleado”.
4. Se clickea en el botón “Guardar” del formulario.
5. Al guardar el empleado, si no hubo ningún problema, se redirecciona a una pantalla que muestra el empleado recien editado y se muestra el mensaje: “El empleado nombre_apellido ha sido editado” (Fin).
   5.1. Al guardar el empleado, si hubo algún problema, se redirecciona a la pantalla de editar empleado y se muestra el mensaje:  “No se ha podido actualizar el empleado nombre_apellido”, si es posible, el mensaje deberá especificar el motivo (Pasar a 3).

## Eliminar Empleado

### Flujo Principal
1. En la interfaz de empleados, se muestra por defecto una tabla con la lista de empleados, cada registro de la tabla tiene un botón para eliminarlo, la opción eliminar también se encuentra en el formulario Mostrar Empleado.
2. Al clickear en el botón “Eliminar” se muestra un mensaje de confirmación: “¿Desea eliminar el empleado nombre_apellido?” con las opciones “Si” “No”.
3. La opción “No” cancela el borrado. La opción “Si” borra el empleado, muestra la lista de empleados, y muestra el mensaje “El empleado nombre_apellido ha sido eliminado”

## Mostrar Empleado

### Descripción
1. En la interfaz de empleados, se muestra por defecto una tabla con la lista de empleados, cada registro de la tabla tiene un botón para ver los detalles del registro
   (Nota: Los empleados tienen muchos campos, por eso, en la lista no se muestran todos los datos, para verlos todos, hay que mostrar los datos del empleado).
2. Al clickear en el botón “Ver” se muestran los datos del empleado.
3. En esta pantalla se tienen las opciones “Listar” (Muestra la lista de empleados), “Eliminar” (Permite eliminar el empleado), “Editar” (Muestra el formulario de edición), “Imprimir” (Imprime los datos del empleado).

## Listar Empleado

### Descripción
1. En la interfaz de empleados, se muestra por defecto una tabla con la lista de empleados, cada registro muestra cierto campos concernietes al empleado.
2. Sobre el listado se tiene un campo de busqueda, para buscar sobre cualquier campo de la lista. También se tiene un botón de “Busqueda Avanzada” que desplegará más campos, para filtrar los datos de la lista, de una manera más específica.
3. En esta pantalla se tienen las opciones: “Nuevo Empleado” (Permite agregar un nuevo empleado), “Ver”, “Editar”, “Eliminar”, por cada registro de la lista, y una opción “Imprimir” (que imprime la lista de empleados con los datos que muestra la lista actual)
4. La lista tiene paginación.

## Dependencias

Ninguna 

## Gemas necesarias
1. Devise 3.0
2. Ransack 1.7.0
3. Kaminari 0-17
4. jQuery Validation Plugin – v1.15.0
5. Input Mask plugin for jquery – v0.0.0

## Prioridad

10

**Comment by rofaccess** [comment]
Pase a In Progress estando desconectado y no me di cuenta.

**Tiempo Utilizado:** 00h30m

**Comment by KariSanabria** [comment]
Había pensado que hay explicaciones repetidas, pero después de tu aclaración @rofaccess creo que se entiende mejor así el flujo del mismo.
Ok para cerrar!

**Comment by Lesfig** [comment]
Adelante Rodrigo, puedes cerrar :)
