### ISSUE TITLE
Definir la documentación para el feature Configuracion 

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#29]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by Lesfig** [comment]
# Configuración para setear datos de la empresa

## Descripción

En Configuraciones de Datos de la empresa, se podrá modificar datos de la empresa como el nombre de la empresa, direccion, telefono, email, sitio web, horario de atención y el logo de la empresa

## Flujo.

1- El usuario solicita al sistema acceder a la interfaz de configuraciones para editar(o ver)
   1.1 Si no existe una configuración en la base de datos, este lo crea automáticamente con los        datos de la empresa predefinidas, y el usuario podrá ver automáticamente dichos datos en la interfaz.

2- El usuario edita los datos necesarios, y selecciona el botón guardar cambios. 

3- Los datos son validados, si está todo correctamente definido se actualizan los cambios y el usuario podrá ver un mensaje de éxito. Si modifica el logo ya tendrá a la vista los cambios como es en el menú y el login, además de la interfaz de configuración.
 3.1 Si algún campo no cumple con la validación (punto 3) tendrá el mensaje correspondiente del porqué no se pudo guardar el dato debajo del mismo.

3- Para que los datos sean aceptados por el sistema deben cumplir con lo siguiente:
Nombre: Debe estar definida siempre, tamaño mínimo de 2 y max de 50
direccion:  Debe estar definida siempre, tamaño mínimo de 4 y max de 100 
telefono: solo acepta números, espacios y paréntesis,tamaño maximo: 20
logo: Cualquier imagen
Horario de Atención: tamaño max: 100
email:   con el formato de un correo ej aasaaaa@algo.com, tamaño max: 30
sitio web:  tamaño max: 40

## Dependencias

No hay abms que dependan netamente de configuraciones, pero se utilizan algunos datos de la empresa en el login, menú(layout), y al imprimir informes, fichas, etc.

## Gemas necesarias

Se utilizarán las siguientes gemas:
1. Carrierwave

## Prioridad: 5

tiempo utilizado 1h:00m

**Comment by Lesfig** [comment]
@rofaccess y @KariSanabria opiniones!

**Comment by rofaccess** [comment]
Para mi que especifica todo lo necesario. Creo que ya podes cerrarlo.

**Comment by KariSanabria** [comment]
Creo que esta todo muy claro.

**Comment by Lesfig** [comment]
tiempo utilizado 1h:00m
