### ISSUE TITLE
Agregar y configurar la gema Devise

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#3]
Se requiere agregar la gema Devise https://github.com/plataformatec/devise al proyecto y realizar las siguientes configuraciones:
- Los usuarios no pueden registrarse, la alta de usuario se realizará a través del ABM de usuarios. Ver [Registerable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Registerable)
- La contraseña del usuario se guardará como un hash en el modelo user. Ver [Database Authenticatable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/DatabaseAuthenticatable)
- Si el usuario está media hora inactivo se volverá a solicitar la autenticación del usuario. Ver [Timeoutable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Timeoutable)
- No se utilizarán las opciones concernientes al uso de email.
- Rutas para el login y logout. Ver [Add sign_in and sign_out](https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template)
- Agregar mensajes en español (ver **I18n** en la documentación de devise).
- La cuenta de usuario debe bloquearse por media hora luego de 5 intentos fallido de login. Ver [Lockable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Lockable)
- La contraseña debe tener una longitud mínima de 8 y máxima de 20. Debe contener una combinación de números, letras (minúsculas y mayúsculas) y símbolos. Ver [Validatable](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Validatable)
- Agregar superusuario. Ver [Add an admin role](https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-Role)

Para saber más consultar la [wiki](https://github.com/plataformatec/devise/wiki) de la gema

**Comment by bordonwork** [comment]
Se requiere agregar la gema Devise https://github.com/plataformatec/devise al proyecto y realizar las siguientes configuraciones:

- Los usuarios no pueden registrarse, la alta de usuario se realizará a través del ABM de usuarios. Ver [Registerable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Registerable)

- La contraseña del usuario se guardará como un hash en el modelo user. Ver [Database Authenticatable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/DatabaseAuthenticatable)

- Si el usuario está media hora inactivo se volverá a solicitar la autenticación del usuario. Ver [Timeoutable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Timeoutable)

- No se utilizarán las opciones concernientes al uso de email.

- Rutas para el login y logout. Ver [Add sign_in and sign_out](https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template)

- Agregar mensajes en español (ver **I18n** en la documentación de devise).

- La cuenta de usuario debe bloquearse por media hora luego de 5 intentos fallido de login. Ver [Lockable](http://rubydoc.info/github/plataformatec/devise/master/Devise/Models/Lockable)

- La contraseña debe tener una longitud mínima de 8 y máxima de 20. Debe contener una combinación de números, letras (minúsculas y mayúsculas) y símbolos. Ver [Validatable](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Validatable)

- Agregar superusuario. Ver [Add an admin role](https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-Role)

Para saber más consultar la [wiki](https://github.com/plataformatec/devise/wiki) de la gema

**Comment by rofaccess** [comment]
Instrucciones:
1. Bajar la rama  issue-3-Agregar_y_configurar_devise
    `git pull origin issue-3-Agregar_y_configurar_devise`
2. Ejecutar
    `bundle install`
3. Ejecutar
   `rake db:migrate`
4. Ejecutar 
   `rake db:seed`  
El comando anterior carga la tabla users con los siguientes datos para poder loguearse:
email: 'admin@gmail.com'
password: 'MyAdmin123', 

Notas: 
1. La base de datos ya debe existir, si no existe, ejecutar
`rake db:create`

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 8.5 horas

**Comment by rofaccess** [comment]
@louvelaz 
Agregue la gema tzinfo-data ya que es un requerimiento para usuarios de Windows. Sin esta gema, el comando "rake db:migrate" causa un error que pide que se instale la gema mencionada

También debes tener instalado [NodeJS](https://nodejs.org/) en tu máquina.
