### ISSUE TITLE
Definir la documentación para el feature Pacientes

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#30]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by KariSanabria** [comment]
# Feature de Pacientes

## Descripción

Actor paciente es la persona que acude a la institución a solicitar un turno para una consulta.
En el abm paciente, se podrá registrar un nuevo paciente al sistema como  así también se podrá listar, editar y eliminar los datos de los mismos.

## Flujo
1. El empleado, en este caso la secretaria accede a la interfaz de paciente.
2. Al iniciar esta interfaz se mostrara una lista de los pacientes registrados en el sistema.
3. Para registrar un nuevo paciente, se tendrá un botón “agregar paciente” el cual contiene un formulario con todos los datos personales como nombres, apellidos, C.I, fecha de nacimiento, dirección,teléfono y otros datos necesarios.
- Cada uno de estos campos estarán  validados, por ejemplo:
- Los nombres y apellidos tendrán un límite inferior de 3 caracteres y límite superior de 30 caracteres.
- Dirección tendrá un límite superior de 125 caracteres.
- C.I debe aceptar a partir de 4 caracteres.
- Teléfono no deber permitir ingresar letras.
- El correo debe tener el formato correcto - algo@algo.com
- Mostrara que campos son obligatorios en el formulario. Los labels tendrá (*) a parte de los mensajes de las validaciones.
  4.A medida que se cargue los datos, el sistema emitirá mensajes de validaciones en caso de que la carga sea errónea.
  5.El sistema tendrá un botón cancelar, para cancelar el registro de un paciente por los motivos que fuere.
  6.Una vez guardada el formulario el sistema emitirá un mensaje que se guardó con éxito al nuevo paciente.
  7.En la lista de pacientes se tendrán iconos en caso de querer editar o eliminar cualquiera de los pacientes.
- En caso de tener muchos datos del paciente se podría tener la opción de ver, para mostrar todos los datos que no se puedan visualizar en la lista de pacientes.
- En la lista de pacientes, se tendrá la opción para buscar o filtrar datos de los mismos.
- **Para editar**, el empleado simplemente elije el paciente a editar, edita los datos necesarios y selecciona el botón guardar y se actualizaran los datos. El formulario editar tendrá todas las validaciones correspondientes.
- **Para eliminar**, un paciente, se selecciona el paciente a ser borrado y con el icono borrar, lo borra, antes de eliminar el sistema emitirá un mensaje “Desea eliminar al paciente nombre_apellido_del_paciente”. Este borrado sería un borrado ocioso.

8.También se podrá imprimir la lista de todos los pacientes.

## Gemas

Se utilizaran las sgtes gemas:
Para validaciones – “ jquery-validate plugin”
Para paginación – “Kaminari”
Para búsqueda –  “ransack”

## Dependencias

Este feature no depende de otros.

## Prioridad: Alta

**Comment by KariSanabria** [comment]
@rofaccess @Lesfig espero sugerencias o cambios que crean conveniente para realizar a este feature.

**Comment by bordonwork** [comment]
Incluir la sección Gemas y Librerías así como lo especifica el issue

**Comment by rofaccess** [comment]
No se si habría que especificar todos los campos para el formulario, y sus respectivos límites aquí, o solo seremos más detallistas en el diseño de interfaces, ya que, aparte de lo menciondado estan la fecha de nacimiento, edad,etc.

**Comment by bordonwork** [comment]
El tema de los campos y validaciones se especificara en el diseño de las
interfaces

**Comment by KariSanabria** [comment]
Pensé que no era necesario especificar todos los campos aquí , por ende puse algunos como ejemplo nomas.

**Comment by rofaccess** [comment]
La verdad que en comparación a lo que hice con #28, este dice todo en de forma más reducida y me está gustando más. 
Creo que ya podes cerrarlo

**Comment by KariSanabria** [comment]
# Feature Pacientes

## Descripción

Actor paciente es la persona que acude a la institución a solicitar un turno para una consulta. En el ABM paciente, se podrá registrar un nuevo paciente al sistema como así también se podrá listar, editar y eliminar los datos de los mismos. 

## Agregar Paciente

### Flujo Principal
1. En la interfaz de paciente, se muestra por defecto una tabla con la lista de pacientes con sus datos. 
2. En el lado izquierdo de la interfaz se muestra un menú lateral, en la misma se encuentra la lista de los nombres de los pacientes de una manera resumida y para un acceso rápido, en la parte superior se tiene el botón “Crear Paciente”.
3. Al clickear en el botón “Crear Paciente” se muestra el formulario de “Nuevo Paciente”.
4. Se especifican todos los datos del paciente, a medida que se van cargando los datos, los mismos ya se van validando, si es que hay alguna restricción que cumplir. Algunos campos aceptan sólo números, otros son obligatorio.
5. Se clickea en el botón “Guardar” del formulario.
6. Al guardar el paciente, si no hubo ningún problema, se muestra el mensaje: “El paciente nombre_paciente ha sido guardado”.
7. Al guardar el empleado, si hubo algún problema, se muestra el mensaje: “No se ha podido guardar el paciente nombre_paciente”, si es posible, el mensaje deberá especificar el motivo.

## Editar Paciente

### Flujo Principal
1. En la interfaz de paciente, se muestra por defecto una tabla con la lista de pacientes con sus datos, cada registro de la tabla tiene un botón para editarlo. 
2. Al clickear en el botón “Editar” se muestra el formulario de “Editar Paciente”.
3. También se podrá editar un paciente a través  de la interfaz de ver paciente cuyo formulario tiene el botón “Editar”, a este formulario se puede acceder en todo momento desde  el menú lateral que se encuentra en la parte izquierda de la interfaz con los nombres de los pacientes de una manera resumida y para un acceso rápido.
4. Se modifican los datos necesarios. Las restricciones de validación son las mismas que en “Nuevo Paciente”.
5. Se clickea en el botón “Guardar” del formulario. Y se actualizan los datos
6. Al guardar el paciente, si no hubo ningún problema, se muestra el mensaje: “El paciente nombre_paciente ha sido actualizado”.
7. Al guardar el paciente, si hubo algún problema, se muestra el mensaje: “No se ha podido actualizar el empleado nombre_paciente”, si es posible, el mensaje deberá especificar el motivo.

## Eliminar Paciente

### Flujo Principal
1. En la interfaz de paciente, se muestra por defecto una tabla con la lista de pacientes, cada registro de la tabla tiene un botón para eliminarlo.
2. También se podrá eliminar un paciente a través  de la interfaz de ver paciente cuyo formulario tiene el botón “Eliminar”, a este formulario se puede acceder en todo momento desde  el menú lateral que se encuentra en la parte izquierda de la interfaz con los nombres de los pacientes de una manera resumida y para un acceso rápido..
3. Al clickear en el botón “Eliminar” se muestra un mensaje de confirmación: “¿Desea eliminar al paciente nombre_paciente?” con las opciones “Si” “No”. Este borrado seria un borrado ocioso.
4. La opción “No” cancela el borrado. La opción “Si” borra el paciente, muestra la lista de pacientes, y muestra el mensaje “El paciente nombre_paciente ha sido eliminado”

## Mostrar Empleado

### Descripción
1. En la interfaz de paciente, se muestra por defecto una tabla con la lista de pacientes con sus datos.
2. En el lado izquierdo de la interfaz se muestra un menú lateral, en la misma se encuentra la lista de los nombres de los  pacientes de una manera resumida y para un acceso rápido. 
3. Al clickear  en uno de los nombres del paciente se muestran el formulario de pacientes con todos los datos.
4. En la parte inferior izquierdo de este formulario se tiene los botones  con las opciones “Eliminar” (Permite eliminar el paciente), “Editar” (Muestra el formulario de edición para modificar).

## Listar Empleado

### Descripción
1. En la interfaz de paciente, se tiene por defecto una tabla con la lista de pacientes. (Nota: Los pacientes tienen muchos campos, por eso, en la lista no se muestran todos los datos.
2. Se tiene la opción de búsqueda.
3. En la interfaz de paciente, en la parte izquierda se tiene un menú lateral con la opción “Listar Pacientes” desde el cual se puede acceder en todo momento a la lista mencionada en el PUNTO 1. 
4. Cada registro de la tabla tiene la opción para editar y eliminar al paciente.
5. Se puede imprimir la lista de todos los pacientes.
6. La lista tiene paginación.

## Dependencias

Ninguna

## Gemas necesarias
1. jQuery Validation Plugin – v1.15.0 
2. Kaminari 0-17 
3. Input Mask plugin for jquery 
4. Ransack 1.7.0 

## Prioridad

10

**Tiempo Utilizado**: 02:30m

**Comment by KariSanabria** [comment]
@rofaccess @Lesfig le hice unos pequeños cambios, y si están de acuerdo para poder cerrar.

**Comment by rofaccess** [comment]
Adelante.
