### ISSUE TITLE
Definir la documentación para el feature Permisos por Rol

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#31]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by rofaccess** [comment]
# Feature Pemisos por Rol:

## Descripción

En esta sección se puede agregar/editar/eliminar roles de usuario, asi también se permitirá epecificar los permisos que tiene cada rol.
Se ingresa a la interfaz de Permisos por Rol, a través del menú Roles

## Agregar Rol

### Flujo Principal
1. En la interfaz de Roles, se muestran dos columnas, en la columna izquierda se listan todos los roles, en la columna derecha se muestra todos los menú y submenu accesibles para el primer rol de la lista.
2. La opción “Agregar Rol” muestra el formulario de nombre de rol y menus-submenus accesibles en la columna derecha de la interfaz.
3. Se especifica el nombre del rol y se setean las interfaces accesibles con unos checkboxes. Se valida que el nombre del rol ya no este en la base de datos, antes de guardarlo.
4. Se guarda el rol y sus permisos con el botón “Guardar”.
5. Al guardar el rol, si no hubo ningún problema, se muestra en la columna derecha el rol recien guardado en modo de edición y se muestra el mensaje: “El rol nombre_rol ha sido guardado” (Fin).
   5.1. Al guardar el rol, si hubo algún problema, se muestra en la columna derecha el formulario de nuevo rol, se muestra el mensaje: “No se ha podido guardar el rol nombre_rol” si es posible, el mensaje deberá especificar el motivo (Pasar a 3).

## Editar Rol

### Flujo Principal
1. En la interfaz de Roles, se muestran dos columnas, en la columna izquierda se listan todos los roles, en la columna derecha se muestra todos los menú y submenu accesibles para el primer rol de la lista.
2. Por cada fila de la lista de roles se tiene la opción “Editar”, que muestra el formulario de edición del nombre de rol y de seteo de las interfaces accesibles. El nombre de rol es validado.
3. Se guarda el rol y sus permisos con el botón “Guardar”.
4. Al guardar el rol, si no hubo ningún problema, se muestra el mensaje: “El rol nombre_rol ha sido actualizado” (Fin).
   4.1. Al guardar el rol, si hubo algún problema, se muestra el mensaje: “No se ha podido actualizar el rol nombre_rol” si es posible, el mensaje deberá especificar el motivo (Pasar a 3).

## Eliminar Rol

### Flujo
1. En la interfaz de Roles, se muestran dos columnas, en la columna izquierda se listan todos los roles, en la columna derecha se muestra todos los menú y submenu accesibles para el primer rol de la lista.
2. Por cada fila de la lista de roles se tiene la opción “Eliminar”.
3. Al clickear en la opción “Eliminar” se muestra un mensaje de confirmación: “¿Desea eliminar el rol nombre_rol?” con las opciones “Si” “No”.
4. La opción “No” cancela el borrado. La opción “Si” borra el rol, actualiza la lista de roles, y muestra el mensaje “El rol nombre_rol ha sido eliminado”
   4.1. Si hubo un problema al borrar el rol, se muestra el mensaje: “No se ha podido eliminar el    rol nombre_rol”, especificando el motivo.
   (Nota: Esto se puede dar en el caso de que haya usuarios que estén relacionados al rol que se  quiere eliminar, mientras haya un usuario relacionado, el rol no se puede eliminar).

## Dependencias

Ninguna 

## Gemas necesarias
1. Cancan 2.0
2. Rolify 5.1.0
3. jQuery Validation Plugin – v1.15.0

## Prioridad

10

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 01h00m
