### ISSUE TITLE
Definir la documentación para el feature Perfil de Usuario 

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#32]
Se requiere definir la documentación necesaria en donde se especifique:
### Descripción

En esta sección se deberá describir el feature, su utilidad para el negocio, los actores, las vistas necesarias (y su propósito), entre otro detalles que ayuden a comprender el objeto del feature.  
### Flujo

Para cada formulario del feature se requerirá especificar:
- Flujo del formulario: esto incluye el flujo de carga del formulario, así como lo procesos que ocurren por detrás (actualización de registros por ejemplo).
- Flujo alternativo: otro flujo que pueda seguirse.
- Excepciones: casos en los que no se podrá guardar los datos del formulario.
- Mensajes: de éxito, error o advertencias (excluir aquellos de validación). 

**Nota:** con respecto a los flujos y excepciones, éstos deben redactarse desde el punto de vista del formulario, no del proceso del negocio (por lo tanto se excluyen referencias como: el paciente llega y pide un turno).
### Dependencias

Se debe especificar las dependencias con otros features, y explicar en qué consisten dichas dependencias.
### Gemas y librerías necesarias

En esta sección se deberá incluir las gemas que se utilizarán para el feature. Se debe especificar para cada vista del feature que gemas se utilizan, la versión de la gema y para que se utiliza dicha gema.
### Prioridad

La prioridad del feature dentro del proyecto en una escala del 1 al 10 (en donde 10 es la prioridad más alta).

**Comment by Lesfig** [comment]
# Feature Perfil de Usuarios:

## Descripción

En esta sección el usuario podrá editar algunos de sus datos como username y/o contraseña.

## Modificar Perfil de Usuario

## Flujo Principal

1- En la interfaz Perfil, se muestra el formulario de Perfil de usuario con los datos del usuario que ha iniciado sesión y está utilizando el sistema.

2- El usuario edita su/s dato/s y selecciona el botón "guardar cambios".

3- El username, antes de guardar,(si es que se modificó) se debe validar si ya existe o no un usuario con ese username.
    3.1 Si es que ya existe un usuario con el mismo username, Se muestra un mensaje "Ya existe el   usuario nombre_usuario", en la pantalla de Perfil de Usuarios con los datos sin modificarse.

4- Al guardar el usuario, si no hubo ningún problema, se redirecciona a una pantalla que muestra el usuario recién modificado y se muestra el mensaje: “El usuario nombre_usuario ha sido modificado”

## Dependencias

Depende del feature usuarios, ya que primeramente debe existir un usuario, dicho usuario debe estar logueado para editar su perfil.

## Gemas necesarias

Devise 3.0

## Prioridad

3

**Comment by rofaccess** [comment]
Faltaria especificar que la contrasena no sera visible mientras se lo escribe y por ende se necesitara un campo confirmar contrasena y ya podras cerrar el ticket.

**Comment by Lesfig** [comment]
# Feature Perfil de Usuarios:

## Descripción

En esta sección el usuario podrá editar algunos de sus datos como username y/o contraseña.

## Modificar Perfil de Usuario

## Flujo Principal

1- En la interfaz Perfil de Usuario, se muestra el formulario de Perfil de usuario con los datos del usuario que ha iniciado sesión y está utilizando el sistema. También habrá un panel en el lado izquierdo con la foto, y datos del usuario debajo de la foto.

2- El usuario edita su/s dato/s (también podrá elegir una imagen), el campo contraseña no sera visible mientras el usuario escribe, por ende habrá un campo confirmar contraseña. Luego el usuario debe seleccionar el botón "guardar".

3- El username, antes de guardar,(si es que se modificó) al igual que el email, se debe validar si ya existe o no un usuario con ese username o email.
3.1 Si es que ya existe un usuario con el mismo username o email, Se muestra un mensaje "Ya existe el usuario nombre_usuario" o "Ya existe un usuario con email", en la pantalla de Perfil de Usuarios con los datos sin modificarse.

4- Al guardar el usuario, si no hubo ningún problema, se redirecciona a una pantalla que muestra el usuario recién modificado y se muestra el mensaje: “El usuario nombre_usuario ha sido modificado”

## Dependencias

Depende del feature usuarios, ya que primeramente debe existir un usuario, dicho usuario debe estar logueado para editar su perfil.

## Gemas necesarias

Devise 3.0

## Prioridad

3

**Comment by Lesfig** [comment]
Tiempo utilizado 01h:00m
