### ISSUE TITLE
Actualizar el Modelo Físico de la DB

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#33]
Se requiere actualizar el diseño de la base de datos.
## Importante

Una vez que los miembros del equipo estén de acuerdo con los cambios hechos deberán enviar el modelado al profesor Samaniego. Hecho esto podrán cerrar la tarea

**Comment by rofaccess** [comment]
Todavía falta agregar 5 fichas, aún así le envié al profe, porque recién a la tarde-noche voy a estar continuando y ya será muy tarde.

Con lo que hay hasta ahora ya se entiende lo que pretendemos hacer.

**Comment by KariSanabria** [comment]
En la reunión de Equipo, quedo todo :+1:

**Comment by bordonwork** [comment]
@rofaccess , @KariSanabria y @Lesfig lo cierro pues ya acabó el sprint 3, nuevos cambios a la db se realizarán en los siguientes sprint cuando hallan definido las fichas.
