### ISSUE TITLE
Diseñar el ABM de Pacientes

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#34]
En base a la descripción del issue #30 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by KariSanabria** [comment]
Así va quedando la vista de crear paciente, falta algunos detalles aún, estoy trabajando en ello.
![nuevo paciente](https://cloud.githubusercontent.com/assets/3719740/14238957/ddd4df8c-fa04-11e5-8d14-40962dc825bf.png)

**Comment by KariSanabria** [comment]
**Tiempo Utilizado:** 1h:00m

**Comment by KariSanabria** [comment]
![nuevo paciente2](https://cloud.githubusercontent.com/assets/3719740/14270397/c32f5876-fabb-11e5-9390-e945c63db97f.png)
![ver paciente2](https://cloud.githubusercontent.com/assets/3719740/14270398/c3319f78-fabb-11e5-8b58-9533ed540eaf.png)
![editar paciente2](https://cloud.githubusercontent.com/assets/3719740/14270395/c3281c96-fabb-11e5-8372-bbe26b8bb6ad.png)
![listar pacientes](https://cloud.githubusercontent.com/assets/3719740/14270396/c32ca4aa-fabb-11e5-9656-3025551cc3d3.png)

**Comment by KariSanabria** [comment]
**Tiempo Utilizado**: 4h:30m

**Comment by KariSanabria** [comment]
Actualizo la vista Listar Pacientes @rofaccess  @Lesfig. Me falto Agregarle la opción de búsqueda y para imprimir :)

![listar pacientes](https://cloud.githubusercontent.com/assets/3719740/14283103/b2c3e98a-fb0f-11e5-999b-1f061e65cf95.png)

**Comment by Lesfig** [comment]
Todo ok.. :+1:

**Comment by rofaccess** [comment]
Esta todo bien
