### ISSUE TITLE
Diseñar el ABM de Turnos

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#35]
En base a la descripción del issue #22 diseñar las vistas:
- Listar
- Nuevo
- Editar
- Ver
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by Lesfig** [comment]
Subo algunas vistas que creé, ésto aún no está terminado, ni nada definido(como colores, ni nada)
@rofaccess y @KariSanabria 
![turnos](https://cloud.githubusercontent.com/assets/6785488/14199232/9114719a-f7b0-11e5-997d-f17528e5e60b.png)
![turnos3](https://cloud.githubusercontent.com/assets/6785488/14199243/b40fa3d6-f7b0-11e5-81b5-1e0b8084b0c4.png)
![turnos5](https://cloud.githubusercontent.com/assets/6785488/14199251/be8d1924-f7b0-11e5-9013-650d7e993db4.png)
![turnos2](https://cloud.githubusercontent.com/assets/6785488/14199255/c88b97c0-f7b0-11e5-822e-900a7d8f1f25.png)

**Comment by Lesfig** [comment]
Los colores, si vamos a usar ese cuadro gris, y lo demás, no está definido.. esto es solo para tener una base

**Comment by Lesfig** [comment]
![turnosnuevo](https://cloud.githubusercontent.com/assets/6785488/14224242/fac63e26-f863-11e5-9226-3ed7baf22761.png)
![turnosnuevo2](https://cloud.githubusercontent.com/assets/6785488/14224246/ffff5db4-f863-11e5-8ffb-dc578a173279.png)
![turnosnuevo3](https://cloud.githubusercontent.com/assets/6785488/14224247/04c3d0be-f864-11e5-8be1-650929bac140.png)

**Comment by rofaccess** [comment]
No se si el panel lateral lo pusiste a modo de ejemplo, pero si lo vas a usar debes quitar el select para setear el área, del formulario de asignar turno, ya que es redundante.
Creo que en la documentacion de requerimientos se especificó un modal para cargar el número de factura, este modal no es necesario, ya que si eliges la opcion si para "Abonará el monto estipulado" se debería mostrar el input para setear el numero de factura, dentro del mismo formulario de asignar turno, de hecho ya lo tienes en tu primer diseño, por lo que el tercer diseño que muestra el modal es redundante.

Tu segunda interfaz al parecer, solo lista los turnos activos del día. 
Si esto lo vas a hacer así, se necesitará otra interfaz para listar turnos, que te liste absolutamente todos los turnos, ya sea nuevos (esto sería activo), atendidos, cancelados. Ahora, esta otra interfaz, con el simple hecho de escribir nuevo en el input de busqueda ya te va a filtrar los turnos activos, si además se tiene una búsqueda avanzada se puede especifica un estado nuevo de un area determinada y te filtrará solo los turnos activos del area que especificaste.

Creo que pretendías hacer algo personalizado para el empleado que asigna el turno, porque consideraste que solo le sería útil ver los turnos activos del día en un area especificada. 
Para generalizar más tu idea, te propongo que en el menú lateral te muestre un calendario para setear una fecha, debajo del calendario se liste las áreas, y debajo de las areas se listen los estados, así puedes usar tu panel lateral para filtrar la lista, osea, seleccionas una fecha, seleccionas un area, seleccionas un estado, y automáticamente en la lista te muestra los turnos en la fecha que especificaste, del area y estado que especificaste. O sea que vendría a ser una búsqueda avanzada con puros click, sería como una UI moderna digamos. Es otra forma de hacer lo mismo que queríamos hacer, en la búsqueda avanzada que pretendíamos implementar para todos los abm.

**Comment by Lesfig** [comment]
De hecho que me faltó colorear el select de Área, va a figurar ese campo pero no se va a poder cambiar al igual que los demás. El modal de factura solo agregué para ver cual escogemos XD Y lo de listas, me parece que le va a ser mucho más productivo al secretario ver los turnos activos nada más en la opción listas de cada área(bueno es solo una opinión mía), lo que faltaría es agregar un opción en todos los submenús como en la segunda interfaz de Reportes turnos. O "Acta de turnos" en la que se liste todo los turnos de todas las áreas con sus estados y demás cosas. No sé si es necesario complicarnos tanto con la opción búsqueda avanzada, se podría hacer de la manera simple nomas.

**Comment by Lesfig** [comment]
![crearturno](https://cloud.githubusercontent.com/assets/6785488/14269547/b2da2fda-fab3-11e5-83fb-81c235f33bef.png)
![editarturno](https://cloud.githubusercontent.com/assets/6785488/14269548/b2dce0d6-fab3-11e5-9066-67024404e0b0.png)
![listaturno](https://cloud.githubusercontent.com/assets/6785488/14269549/b2e5cba6-fab3-11e5-9688-887e1a31e050.png)
![listaturnoespecifico](https://cloud.githubusercontent.com/assets/6785488/14269550/b2f04b30-fab3-11e5-90ca-53a82a815970.png)
![verturno](https://cloud.githubusercontent.com/assets/6785488/14269551/b2f949a6-fab3-11e5-8a84-4a12297da10d.png)

**Comment by Lesfig** [comment]
@KariSanabria y @rofaccess

**Comment by Lesfig** [comment]
Cuando se clickea en el botón más de paciente, mostrará el mismo formulario del issue #34 pero en un modal

**Comment by Lesfig** [comment]
tiempo utilizado: 04h:00m

**Comment by rofaccess** [comment]
Esta todo ok.
