### ISSUE TITLE
Diseñar el ABM de Permisos por Rol

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#36]
En base a la descripción del issue #31 diseñar las vistas:
- Listar
- Nuevo
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by Lesfig** [comment]
![crearroles](https://cloud.githubusercontent.com/assets/6785488/14265494/c9c79076-fa8f-11e5-8ca6-bd00f69bd033.png)
![verroles](https://cloud.githubusercontent.com/assets/6785488/14265817/c6f27a08-fa91-11e5-9504-098798944d30.png)

![editarroles](https://cloud.githubusercontent.com/assets/6785488/14265508/d55fc598-fa8f-11e5-8c86-f6636b363cda.png)
![editarroles2](https://cloud.githubusercontent.com/assets/6785488/14265507/d55facc0-fa8f-11e5-8d5d-24644c2792ef.png)

Tiempo utilizado: 2h:00m

**Comment by rofaccess** [comment]
Esta todo ok

**Comment by KariSanabria** [comment]
Todo :+1:

**Comment by Lesfig** [comment]
**Tiempo utilizado: ** 2h:00m
