### ISSUE TITLE
Diseñar el ABM de Horarios de Atención

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#37]
En base a la descripción del issue #25 diseñar las vistas:
- Listar
- Nuevo
- Editar
- Ver
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by rofaccess** [comment]
![listar horario](https://cloud.githubusercontent.com/assets/2489653/14269615/60310154-fab4-11e5-9322-a41fcee444cd.png)
![agregar horario](https://cloud.githubusercontent.com/assets/2489653/14269617/63d9ba08-fab4-11e5-9292-2f9a32de8a84.png)
![mostrar horario](https://cloud.githubusercontent.com/assets/2489653/14269618/6b9d5862-fab4-11e5-9c3b-47787e7d73ee.png)
![editar horario](https://cloud.githubusercontent.com/assets/2489653/14269621/7969de5c-fab4-11e5-9065-c731caec90f3.png)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 05h00m
