### ISSUE TITLE
Diseñar la vista Reporte Estadistico

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#38]
En base a la descripción del issue #26 diseñar las vistas:
- Listar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by KariSanabria** [comment]
### Reporte Estadístico por Año

![reporte estadistico por ano](https://cloud.githubusercontent.com/assets/3719740/14235473/7234af82-f9cd-11e5-8e7b-31afb02d74aa.png)

### Reporte Estadístico por Mes

![reporte estadistico por mes](https://cloud.githubusercontent.com/assets/3719740/14235477/79bf1986-f9cd-11e5-9fec-b3efaab27c1a.png)

### Reporte Estadístico por Día

![reporte estadistico por dia](https://cloud.githubusercontent.com/assets/3719740/14235492/be1f80b6-f9cd-11e5-92fd-df0eaa42b8cf.png)

**Comment by KariSanabria** [comment]
**Tiempo Utilizado:** 04h:00m

**Comment by rofaccess** [comment]
Esta todo ok

**Comment by Lesfig** [comment]
Me gusta, puedes cerrarlo señorita!
