### ISSUE TITLE
Diseñar la vista Perfil de Usuario

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#39]
En base a la descripción del issue #32 diseñar las vistas:
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by Lesfig** [comment]
![perfil](https://cloud.githubusercontent.com/assets/6785488/14236138/83f263fc-f9de-11e5-9c64-2757e48c96b8.png)
![perfil2](https://cloud.githubusercontent.com/assets/6785488/14236139/8415fb3c-f9de-11e5-9b48-91457fabff99.png)

**Comment by Lesfig** [comment]
Tiempo Utilizado: 03h:00m, por lo cambios realizados

**Comment by rofaccess** [comment]
Esta todo ok.
