### ISSUE TITLE
Agregar el modelo Empleado

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#4]
Depende del issue #3 
Se requiere diseñar el modelado de la tabla empleado y generar el modelo y  migration correspondiente. Esto incluye las tablas relacionadas.
En el modelo se deben especificar las restricciones para cada atributo especificadas en el modelado realizado.

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 4.5 horas

**Comment by rofaccess** [comment]
Ya se integró con development y es accesible en http://cenade-test.herokuapp.com/

Para ejecutar localmente se debe ejecutar:
`rake db:setup`
Porque hay nuevas migraciones y nuevos datos de prueba que cargar en la base de datos.
**Este es el modelo de datos**
![cenade](https://cloud.githubusercontent.com/assets/2489653/13720733/ecb69b9e-e7ee-11e5-8a84-4dacad118b42.jpg)
