### ISSUE TITLE
Diseñar la vista Configuración

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#40]
En base a la descripción del issue #29 diseñar las vistas:
- Editar
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by rofaccess** [comment]
![datos de la empresa](https://cloud.githubusercontent.com/assets/2489653/14293462/b0ccbcee-fb3a-11e5-8533-18488f67e6c7.png)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 01h00m

**Comment by bordonwork** [comment]
@rofaccess aprobado
