### ISSUE TITLE
Diseñar el ABM de Usuarios

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#41]
En base a la descripción del issue #28 diseñar las vistas:
- Listar
- Nuevo
- Editar
- Ver
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by KariSanabria** [comment]
Listar Usuario,el resto me falta algunos detalles.

![listarusuario](https://cloud.githubusercontent.com/assets/3719740/14224722/94363326-f874-11e5-8698-315507baabc0.png)

**Comment by KariSanabria** [comment]
Falta arreglar algunos detalles e iré alzando el resto hoy.

![listarusuario](https://cloud.githubusercontent.com/assets/3719740/14224751/6e292c46-f875-11e5-96ec-47b09b77db0f.png)

**Comment by rofaccess** [comment]
En vez de que en la tabla diga Nombres y Apellidos, creo que sería mejor que diga empleado y que muestre el nombre y apellido juntos, Usuarios debería ser Usuario en la tabla. El Icono de eliminar suele resaltar más con un color rojo. Es Jefa y no Gefa (je je).

**Comment by KariSanabria** [comment]
![nuevo usuario](https://cloud.githubusercontent.com/assets/3719740/14229825/01884d04-f90d-11e5-903f-29c4e3cbb849.png)
![ver usuario](https://cloud.githubusercontent.com/assets/3719740/14229826/019f948c-f90d-11e5-86c6-15ade890a154.png)
![editar usuario](https://cloud.githubusercontent.com/assets/3719740/14229823/0154b412-f90d-11e5-956b-a113df458da7.png)
![eliminar usuario](https://cloud.githubusercontent.com/assets/3719740/14229824/016cf6e4-f90d-11e5-8ac9-b221c7b55250.png)

**Comment by KariSanabria** [comment]
**Tiempo utilizado**: 5h:30m

**Comment by rofaccess** [comment]
Esta todo ok

**Comment by Lesfig** [comment]
Todo ok :)
