### ISSUE TITLE
Diseñar el ABM de Empleados

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#42]
En base a la descripción del issue #27 diseñar las vistas:
- Listar
- Nuevo
- Editar
- Ver (si incluye)
## Importante

Se requiere subir una captura del diseño de las interfaces para ser validado por los demás miembros del equipo

**Comment by Lesfig** [comment]
![empleados1](https://cloud.githubusercontent.com/assets/6785488/14233976/4e496806-f9a5-11e5-8392-1cc34519eeaa.png)

![empleados2](https://cloud.githubusercontent.com/assets/6785488/14233908/c1de28c6-f9a3-11e5-9856-e36d20efe364.png)
![empleados3](https://cloud.githubusercontent.com/assets/6785488/14233910/c1e5ed40-f9a3-11e5-8a7d-8069ae89fd20.png)

Ayer no pude subir mis imágenes

**Comment by Lesfig** [comment]
![empleados1](https://cloud.githubusercontent.com/assets/6785488/14237247/28be57aa-f9ef-11e5-8e59-bb87929ee565.png)
![empleados2](https://cloud.githubusercontent.com/assets/6785488/14237844/64f7193e-f9f7-11e5-863f-b59d7255dbe2.png)
![empleados3](https://cloud.githubusercontent.com/assets/6785488/14237845/64f7855e-f9f7-11e5-9253-df1547325ccf.png)

**Comment by Lesfig** [comment]
Tiempo utilizado: 5h:00m

**Comment by rofaccess** [comment]
Esta todo ok

**Comment by KariSanabria** [comment]
Todo OK :+1:

**Comment by louvelaz** [comment]
@Lesfig @rofaccess @KariSanabria Creo que el campo Email tiene que ser obligatorio para que, como establecen las politicas de usuario,  se pueda pedir restaurar la contraseña por correo electrónico
