### ISSUE TITLE
Diseñar la vista para la Ficha Nutricional Pediátrica

### ISSUE THREAD

**Issue by rofaccess** [rofaccess/CENADE#43]
Este diseño va a ser usado en #23 Feature Atención Profesional y también podría ser usado en #24 Feature Fichas.
No hay un flujo claro sobre esta vista, porque hay que diseñarlo primero y tratar de encontrar la mejor forma de mostrarlo.
Después se definirá el flujo a detalle.

**Comment by rofaccess** [comment]
![base moderna](https://cloud.githubusercontent.com/assets/2489653/14245434/479c6816-fa2f-11e5-9138-a9c403f50de1.png)

**Comment by rofaccess** [comment]
Rato después de asignarme la tarea, había comenzado, pero me olvide de pasar a To Do
Me olvidé de estos: 
1. Encima de los tab que comienzan con antecedente prenatal tiene que haber un titulo CONSULTA
2. Encima de los tab donde esta nuevo control debe haber un título SEGUIMIENTO

**Tiempo Utilizado:** 05h00m

**Comment by rofaccess** [comment]
Quiero hacer constar que la imagen alzada es ya la tercera versión. Cuando el jueves por ahí se tenía que hacer #23 Definir la documentación para el feature Atención Profesional, nos fue imposible verificar un flujo sin tener interfaces tentativas.

Esta fue la primera versión
![consulta2](https://cloud.githubusercontent.com/assets/2489653/14245886/4e92867a-fa32-11e5-8fe8-e5d995b504aa.png)

Esta es la segunda versión, probamos con otra ficha a ver si se podía generalizar
![base simple](https://cloud.githubusercontent.com/assets/2489653/14245895/659b49ba-fa32-11e5-9d23-3bffc7e675c2.png)

**Comment by KariSanabria** [comment]
En la Ficha final, solo faltaría los títulos que mencionaste,y el resto esta todo :+1:

**Comment by Lesfig** [comment]
Opino igual que Kari, solo faltaría los títulos, el resto ok :+1:

**Comment by bordonwork** [comment]
@rofaccess aprobado
