### ISSUE TITLE
Diseñar la vista Ficha para Fonoaudiología

### ISSUE THREAD

**Issue by Lesfig** [rofaccess/CENADE#44]
Este diseño va a ser usado en #23 Feature Atención Profesional y también podría ser usado en #24 Feature Fichas.
No hay un flujo claro sobre esta vista, porque hay que diseñarlo primero y tratar de encontrar la mejor forma de mostrarlo.
Después se definirá el flujo a detalle.

**Comment by Lesfig** [comment]
![fichafonoaudiologia](https://cloud.githubusercontent.com/assets/6785488/14291300/f23ee364-fb30-11e5-8f5b-384dee336783.png)
![fichafonoaudiologia2](https://cloud.githubusercontent.com/assets/6785488/14291599/3bfa7864-fb32-11e5-94d7-2ab53aace407.png)

**Comment by rofaccess** [comment]
Esta todo ok

**Comment by bordonwork** [comment]
@Lesfig aprobado
