### ISSUE TITLE
Implementar el feature Turnos

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#45]
En base a la descripción provista en el issue #20, a las políticas especificadas en el issue #22  y al diseño realizado en el issue #35 implementar el feature turnos

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/turnos/new

**Comment by louvelaz** [comment]
@Lesfig 
- El filtro por "Fecha Consulta" no es intuitivo, en el listado se muestra las fechas en el formtato mm/dd/aaaa, pero en el filtro acepta dd/mm/aaaa
- El botón Limpiar Filtros no funciona
- Cuando sale un mensaje de error, los datos ingresados se resetean
- No se despliega el modal de paciente para agregar un nuevo paciente desde allí

**Comment by louvelaz** [comment]
Moví a To Review este issue el 25/04/2016

**Comment by Lesfig** [comment]
Pasé a done a las 16:35 del 25/04

**Comment by Lesfig** [comment]
@louvelaz  limpiar filtros, solo limpia los campos. Para que aparezca nuevamente todos los turnos hay que apretar filtrar con los campos vacíos, Ahora le cambié el titulo del link por "Limpiar Campos"

**Comment by louvelaz** [comment]
@Lesfig Ok

**Comment by louvelaz** [comment]
Issue cerrado el día 27/04/16
