### ISSUE TITLE
Implementar el feature Perfil de Usuario

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#47]
En base a la descripción provista en el issue #32 y al diseño realizado en el issue #39 implementar el feature Perfil de Usuario

**Comment by louvelaz** [comment]
@KariSanabria 
- Para poder cambiar la imagen, se tiene que hacer clic alrededor del "+Agregar Imagen" , y no sobre el link mismo

![perfil boton cenade](https://cloud.githubusercontent.com/assets/6853236/14592266/b9f75e64-04ea-11e6-970a-08b9a69c0807.jpg)

![perfil boton cenade 4](https://cloud.githubusercontent.com/assets/6853236/14592275/cba91544-04ea-11e6-97eb-fa0dede841b1.jpg)
- Ninguno de los campos tiene el limite inferior que corresponde
- El campo Teléfono puede estar en blanco según el diseño

Sugerencia:
- Estaría bueno poder tener una vista previa de la imagen antes de Guardar, y no solo ver el nombre de la imagen

![perfil boton cenade 2](https://cloud.githubusercontent.com/assets/6853236/14592293/f92850de-04ea-11e6-8397-867ae3f7f8d7.jpg)

**Comment by KariSanabria** [comment]
No implemente la sugerencia, ya que tendría que usar otra gema o de lo contrario realizar una solución para ello, y para no perder tiempo en pequeños detalles como esos, decidimos dejarlo así.

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/perfil_usuarios/edit

**Comment by louvelaz** [comment]
@rofaccess Podrías verme este issue? Creo que ocurrió algo en la integración, esta muy inestable

**Comment by KariSanabria** [comment]
Pasé a Done a las 23:30 del 25/04

**Comment by louvelaz** [comment]
Issue cerrado el día 27/04/16
