### ISSUE TITLE
Actualizar el feature Usuarios

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#48]
En base a la descripción provista en el issue #28, a las políticas especificadas en el issue #19  y al diseño realizado en el issue #41 actualizar el feature **Usuarios**

**Comment by rofaccess** [comment]
**Testear en:** http://cenade-test.herokuapp.com/usuarios

**Nota:** El listado muestra un registro por página, esto es solo para comprobar que la paginación funciona como debería.

**Comment by louvelaz** [comment]
@KariSanabria 
- Hay mensajes que se muestran en ingles

![error](https://cloud.githubusercontent.com/assets/6853236/14553123/0f378a24-02b2-11e6-8cc6-b1c374ae88e0.jpg)
- Cuando en Nombre de Usuario se supera el limite superior o el limite inferior, sale este mensaje de error

![error 2](https://cloud.githubusercontent.com/assets/6853236/14553130/1ac44fee-02b2-11e6-892e-f227e33fca70.jpg)

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/usuarios

**Comment by KariSanabria** [comment]
Muevo Nuevamente este feature para agregar los roles correspondientes realizados en el issue #50 que se había realizado al par que este feature.

**Comment by louvelaz** [comment]
@KariSanabria  Un usuario con los permisos correspondientes puede borrar un usuario Admin cuando en las políticas de usuarios se establece que: Un usuario con los permisos correspondientes para eliminar usuarios, no puede eliminarse a sí mismo, ni a un usuario Admin.

**Comment by louvelaz** [comment]
Moví a To Review este issue el 25/04/2016

**Comment by KariSanabria** [comment]
Pasé a done a las 23:27 del 25/04
@louvelaz  El usuario Admin no puede borrarse a si mismo, lo que arregle fue que tampoco pueda borrar a otro Usuario Admin.

**Comment by louvelaz** [comment]
@KariSanabria Si, lo he visto. Puse la política completa, pero no porque no respetaba ambas cosas.

**Comment by louvelaz** [comment]
Issue cerrado el día 27/04/16
