### ISSUE TITLE
Actualizar el feature Configuración

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#49]
En base a la descripción provista en el issue #29 y al diseño realizado en el issue #40 implementar el feature **Configuración**

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/configuraciones/1/edit

**Comment by louvelaz** [comment]
@KariSanabria 
- El campo Dirección se mueve cuando salen mensajes de error

![dir](https://cloud.githubusercontent.com/assets/6853236/14775031/e98ebe98-0a89-11e6-9925-78bd71599acb.jpg)

![dir 2](https://cloud.githubusercontent.com/assets/6853236/14775036/f22119e8-0a89-11e6-91c6-0126ef409ef1.jpg)
- El campo Usuario Admin se desarregla cuando sale el mensaje de error

![msj](https://cloud.githubusercontent.com/assets/6853236/14775044/005268b4-0a8a-11e6-90e2-c9d78f6fc15c.jpg)
- Si se recarga la pagina despues de editar y de que se hayan actualizado los campos, sale este error:

![error](https://cloud.githubusercontent.com/assets/6853236/14775061/2557638a-0a8a-11e6-8ca4-9d81ec8e5657.jpg)
- Cada vez que se edita algún campo, se tiene que volver a seleccionar un Usuario Admin previamente guardado

**Comment by louvelaz** [comment]
Moví a To Review este issue el 25/04/2016

**Comment by KariSanabria** [comment]
Pasé a Done a las 23:30 del 25/04

**Comment by louvelaz** [comment]
Issue cerrado el día 27/04/16
