### ISSUE TITLE
Implementar el formulario de login

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#5]
Depende de #3 
Implementar el formulario del login el cual deberá contener los siguientes elementos:
- Un campo para usuario.
- Un campo para la contraseña.
- Un botón para hacer login.

Se deberá validar los campos antes de enviar el formulario, tanto su longitud como su formato. Ver: Validatable en issue #3, [jquery-validation](https://github.com/jzaefferer/jquery-validation)

Esta vista debe realizarse en base al formulario generado por devise. Ver: `rails generate devise:install` [en la documentación](https://github.com/plataformatec/devise)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 3 horas

**Comment by louvelaz** [comment]
@rofaccess No se muestran mensajes de contraseña incorrecta o user no encontrado o no existe.

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 30 minutos

**Comment by rofaccess** [comment]
El branch de la tarea ya fue integrado a development.
A partir de ahora se va a testear desde development

**Comment by louvelaz** [comment]
@rofaccess La implementación esta correcta. Lo único que faltaría es arreglar la parte que se corre cuando se muestran mensajes de validación.

![campo](https://cloud.githubusercontent.com/assets/6853236/13625050/92889cfc-e592-11e5-9c63-65c4ea3339d6.jpg)

**Comment by rofaccess** [comment]
Arreglado. También el mensaje "Email o contraseña no validos" se cambio por "Nombre de Usuario o contraseña no validos"

No seguí el procedimiento de los estados. No volverá a pasar

**Tiempo Utilizado:** 2 horas
