### ISSUE TITLE
Implementar el feature Permisos por Rol

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#50]
En base a la descripción provista en el issue #31 y al diseño realizado en el issue #36 implementar el feature **Permisos por Rol**

**Comment by rofaccess** [comment]
Testear en:
http://cenade-test.herokuapp.com/roles

**Comment by louvelaz** [comment]
@Lesfig 
- El limite inferior para Descripción debería ser 3
- Crear Rol, ni Editar Rol no coincide con el diseño especificado, le falta titulo 

![titulo](https://cloud.githubusercontent.com/assets/6853236/14452373/4a0e33b2-005c-11e6-9efa-a2a6a861368c.jpg)

![titulo3](https://cloud.githubusercontent.com/assets/6853236/14452475/d9f8da2c-005c-11e6-9954-31489eeeb3f0.jpg)
- Los permisos no se muestran agrupados como en el diseño:

![permisos](https://cloud.githubusercontent.com/assets/6853236/14452389/63f356ae-005c-11e6-9eb3-2fe50bcdbced.jpg)

![permiso 2](https://cloud.githubusercontent.com/assets/6853236/14452422/84e6576c-005c-11e6-8b02-67f4073b416b.jpg)

**Comment by Lesfig** [comment]
Moví a done este issue a las 03:40 am del  20/04/2016

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/roles

**Comment by louvelaz** [comment]
Moví a To Review este issue el 21/04/2016

**Comment by louvelaz** [comment]
@Lesfig 
- En la barra de paginacion siempre se muestra pintada la pagina 1, aunque no se este mostrando esa pagina

![pag](https://cloud.githubusercontent.com/assets/6853236/14730906/2ce7a790-0819-11e6-80f8-850f1e13109d.jpg)
- La barra de paginacion muestra los últimos 8 roles, y debería mostrar la cantidad que se especifica en la documentación

**Comment by rofaccess** [comment]
Ahora se muestra 20 registros por página (Modifiqué una linea nomás)
Arreglé el problema con la paginación, era una lína con una "r" perdida que borré y funcionó.

**Comment by louvelaz** [comment]
Issue cerrado el día 27/04/16
