### ISSUE TITLE
Implementar el feature Pacientes

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#52]
En base a la descripción provista en el issue #30 y al diseño realizado en el issue #34 implementar el feature **Pacientes**

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/pacientes

Notas:
1. No es exactamente igual al diseño, porque lo dejé parecido a empleados, por lo menos en aquellos datos que son comunes entre empleados y pacientes, tienen la misma estructura.

**Comment by louvelaz** [comment]
Moví a To Review este issue el 25/04/2016

**Comment by louvelaz** [comment]
@rofaccess 
- En el campo Fecha de Ingreso se debería seleccionar una fecha entre los días lunes a viernes, sin embargo en la interfaz se puede seleccionar cualquier día
- En el campo Email se debe poner un \* para indicar que es un campo requerido

![em](https://cloud.githubusercontent.com/assets/6853236/14778163/6601ed8c-0a9f-11e6-92f9-069443a9c393.jpg)
- Los campos que deben tener limites inferiores no los tienen

**Comment by bordonwork** [comment]
@louvelaz y @rofaccess en clase decidimos que:
- La edad se debe calcular automaticamente a partir de la fecha de nacimiento
- Email no debe ser campo obligatorio
- Si el paciente es menor los campos padre, madre o encargado deben estar rellenados (aunque sea uno de ellos)
- La entrada se puede hacer cualquier dia.

**Comment by louvelaz** [comment]
@bordonwork  Ok

**Comment by rofaccess** [comment]
Commit anterior 23:53 - 05 de Mayo

**Comment by rofaccess** [comment]
El commit anterior es del día Sábado 07 de Mayo a las 23:57 horas
Tiempo Utilizado: 01h00m. 
Me olvidé de indicar el tiempo en el commit

**Comment by louvelaz** [comment]
@rofaccess 
- En la barra de paginacion, cuando se quiere ir a la pagina 2 tira este error en la consola
  ![error](https://cloud.githubusercontent.com/assets/6853236/15096380/33e05bf8-14c3-11e6-8bcd-bb36d7a2283b.jpg)
- Cuando se utiliza la Búsqueda, tira un error en la consola
  ![error 2](https://cloud.githubusercontent.com/assets/6853236/15096381/3b680114-14c3-11e6-9a59-d9d14c8aa594.jpg)
- Output de rails_best_practices
  ![pac](https://cloud.githubusercontent.com/assets/6853236/15096383/4350b16e-14c3-11e6-879e-1ab052ee812c.jpg)

**Comment by rofaccess** [comment]
Ok. Gracias, se me pasó totalmente esos errores.
