### ISSUE TITLE
Implementar el feature Ficha(FonoAudiología)

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#53]
En base a la descripción provista en el issue #24 y a las políticas definidas en el issue #21 implementar el feature **Fichas FonoAudiologia**

**Comment by KariSanabria** [comment]
![nueva ficha fonoaudiologia](https://cloud.githubusercontent.com/assets/3719740/14765457/09520ba2-09b0-11e6-9ce0-32ff7b007ff6.png)
![editar ficha fonoaudiologia](https://cloud.githubusercontent.com/assets/3719740/14765458/1481a9ce-09b0-11e6-8873-5217905331e4.png)
![mostrar ficha fonoaudiologia](https://cloud.githubusercontent.com/assets/3719740/14765459/19b419e0-09b0-11e6-9eab-6ddaad59b856.png)

**Comment by KariSanabria** [comment]
@rofaccess  @Lesfig    Así quedarían las fichas, estos diseños tienden a cambios según sugerencias! 
**Tiempo Utilizado:** 02H:30M

**Comment by KariSanabria** [comment]
@rofaccess @Lesfig

**Comment by rofaccess** [comment]
Me parece bien

**Comment by rofaccess** [comment]
Me parece bien. Para asegurar nomás, los datos personales del paciente, yo las diseñaré igual al de Leslie. 
No es necesario que actualices tu diseño solo por ese detalle.

**Comment by KariSanabria** [comment]
La ficha de Fonoaudiologia solo solicita estos campos, lo que agregue fue C.I !!! no quise agregar campos que no figuran en la ficha que nos facilitaron.

**Comment by rofaccess** [comment]
ok. Entiendo

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/fichas_fonoaudiologicas

**Comment by louvelaz** [comment]
@KariSanabria 
- La barra de paginacion muestra los últimos 2 roles y debería mostrar 20, que es la cantidad que se especifica en la documentación
- En Editar Ficha: El campo Paciente no se debería poder editar
- Output de rails_best_practices
  ![fono 2](https://cloud.githubusercontent.com/assets/6853236/15092024/08f77cde-142b-11e6-8091-bd7d72f77de4.jpg)
  ![fono 3](https://cloud.githubusercontent.com/assets/6853236/15092023/08f79dcc-142b-11e6-9727-369992720822.jpg)
  ![fono 4](https://cloud.githubusercontent.com/assets/6853236/15092025/08f97dfe-142b-11e6-85c9-fd4cabeb6657.jpg)
  ![fono 5](https://cloud.githubusercontent.com/assets/6853236/15092026/08fc4cc8-142b-11e6-9bd8-887d02fc0773.jpg)
  ![fono 6](https://cloud.githubusercontent.com/assets/6853236/15092027/08ff71c8-142b-11e6-8af5-9dc393b87a91.jpg)
  ![fono 7](https://cloud.githubusercontent.com/assets/6853236/15092028/0903ceee-142b-11e6-9cd8-4c854b34b6e9.jpg)
  ![fono 8](https://cloud.githubusercontent.com/assets/6853236/15092029/091cea96-142b-11e6-8b17-3697bc49c096.jpg)
  ![fono](https://cloud.githubusercontent.com/assets/6853236/15092030/09213e52-142b-11e6-8e1e-21f20dbbf101.jpg)
