### ISSUE TITLE
Implementar el feature Ficha(Fisioterapia Adultos)

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#54]
En base a la descripción provista en el issue #24 y a las políticas definidas en el issue #21 implementar el feature **Fichas Fisioterapia Adultos**

**Comment by rofaccess** [comment]
![nuevo ficha fisioterapia adulto](https://cloud.githubusercontent.com/assets/2489653/14854502/ff5263a8-0c5d-11e6-8460-645caf7b8614.png)

**Comment by bordonwork** [comment]
@rofaccess tiene muchos campos que parecen más una consulta que una ficha
fija, no podría incluirse en consultas?

**Comment by rofaccess** [comment]
Los datos de la ficha están en general, en el mismo orden en que están en la ficha de fisioterapia adulto.
También puse todos los campos. Ej. motivo consulta, diagnóstico, plan de tratamiento kinésico, etc. sin importar que hubieran o no campos parecidos en la tabla de consultas. 
La intención es representar la ficha tal y como es inherentemente de si la tabla de consultas tenga campos parecidos o no.

Si te parece que es mejor quitar nomás diagnostico, motivo consulta, observación, plan de tratamiento kinésico y evolución, las quito.

De hecho que el resto del grupo no lo está haciendo de esta forma, pero en el modelo de datos yo lo especifique así desde el sábado, tambien comenté al respecto en #57

**Comment by rofaccess** [comment]
Tiempo utilizado: 01h00m

**Comment by bordonwork** [comment]
Si se puede generalizar todo e incluirlo en consultas sería mejor

**Comment by rofaccess** [comment]
Ok. diagnostico, motivo consulta, observación, plan de tratamiento kinésico y evolución no lo tendré en cuenta en la ficha.

**Comment by bordonwork** [comment]
Ok, coordina con leslie para ver sise requerirán en la vista de Consultas

**Comment by rofaccess** [comment]
Testear en : cenade-test.herokuapp.com/fichas_fisioterapeuticas_adultos

**Comment by rofaccess** [comment]
Aclaro que la impresión de la ficha, se debería ver así, En heroku no se ve bien, por un error que tenía, mañana recién voy a alzar el reparado.
![screenshot from 2016-05-05 15-39-24](https://cloud.githubusercontent.com/assets/2489653/15054895/bfc47f16-12d7-11e6-8ecd-50217ca3bee8.png)

**Nota:** No es igual a lo que ya se hizo en otras fichas. Esto es un tentativo para mostrale a mi grupo ya que es no es complicado implementarlo, y a pesar de que los campos sean muy largos, igual se ve bien.

**Comment by louvelaz** [comment]
@rofaccess 
- Output de rails_best_practices
  ![fisio 2](https://cloud.githubusercontent.com/assets/6853236/15092176/5b7f2344-1430-11e6-8628-cf03eb71b4c0.jpg)
  ![fisio 3](https://cloud.githubusercontent.com/assets/6853236/15092177/5b82a9f6-1430-11e6-84be-85e98b8eac34.jpg)
  ![fisio](https://cloud.githubusercontent.com/assets/6853236/15092178/5b86b08c-1430-11e6-89c1-0474bc92ba66.jpg)
