### ISSUE TITLE
Implementar el feature Ficha(Fisioterapia Niños)

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#55]
En base a la descripción provista en el issue #24 y a las políticas definidas en el issue #21 implementar el feature **Fichas Fisioterapia Niños**

**Comment by Lesfig** [comment]
![fisiolista](https://cloud.githubusercontent.com/assets/6785488/14759808/e6f05378-08fd-11e6-8d72-a7d2fcb897be.png)
![fisionew1](https://cloud.githubusercontent.com/assets/6785488/14759809/e6f8690a-08fd-11e6-9468-15037f647c54.png)
![fisioshow1](https://cloud.githubusercontent.com/assets/6785488/14759810/e703f69e-08fd-11e6-9b1e-aaa30fb2f85e.png)

tiempo 02h:30m

**Comment by Lesfig** [comment]
el último es un show pero no le rellené los campos @bordonwork @rofaccess @KariSanabria

**Comment by Lesfig** [comment]
Rubén más arriba ya había hecho mi commit por si se te pierde.. de 1 hora.. y el diseño dos horas y media

**Comment by rofaccess** [comment]
Me parece bien, creo que faltaría el título de la ficha nomás (Ficha de tal cosa), no es necesario que actualizes el diseño, es solo un título.

**Comment by Lesfig** [comment]
cambié a Done a las 03:00 am del 26/04

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/ficha_fisioterapia_ninos

**Comment by louvelaz** [comment]
@Lesfig 
- En el campo Condiciones Generales del Recién Nacido, cuando se ingresa mas de 250 caracteres no se guarda en la base de datos y no muestra el mensaje de error, creo que se debe porque en la base de datos figura max 250 caracteres para este campo, pero en la interfaz permite hasta 500

![cond](https://cloud.githubusercontent.com/assets/6853236/14934787/0d22e4d4-0e8a-11e6-8b5d-aea4fb3580d7.jpg)
- En la barra de paginacion siempre se muestra pintada la pagina 1, aunque no se este mostrando esa pagina

![pag](https://cloud.githubusercontent.com/assets/6853236/14934896/c8a5398e-0e8d-11e6-9ac4-48696b84bcf8.jpg)

**Comment by Lesfig** [comment]
@louvelaz  Sii falta resetear la base de datos de Heroku, y ya se arreglará lo de los limites. Veo lo de la paginación :)
