### ISSUE TITLE
Diseñar la interfaz de Consultas

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#56]
Se requiere diseñar la interfaz gráfica para la vista consultas la cual debe incluir los atributos definidos en el diseño de las fichas.

**Comment by Lesfig** [comment]
![consultalista](https://cloud.githubusercontent.com/assets/6785488/14697450/fd0238d2-0751-11e6-935e-b0fed0a88ce6.png)
![consultashow3](https://cloud.githubusercontent.com/assets/6785488/14697449/fcff4f3c-0751-11e6-8347-616afa94f64b.png)
![consultasnew](https://cloud.githubusercontent.com/assets/6785488/14697451/fd0b12b8-0751-11e6-88fa-ac280ab18c04.png)

El Nuevo tiene la opción ver ficha, pero ese solo aparecerá cuando se selecciona un paciente, Y editar es básicamente lo mismo que nuevo, solo con un botón más abajo que dirá nuevo control

**Comment by Lesfig** [comment]
Tiempo 03h:30m

**Comment by Lesfig** [comment]
@rofaccess @KariSanabria @bordonwork @mirtara @louvelaz

**Comment by bordonwork** [comment]
@Lesfig el abm de control se haría en otra interfaz?

**Comment by rofaccess** [comment]
Quería darte un ok para empezar, pero tristemente tengo estas dudas.
1. El icono + en el listado es para agregar un nuevo control no? Ahora, el nuevo control en la lista y en ver desplegaría un modal, para cargar el nuevo control?
2. Los datos fijos como ser: Antecedentes Postnatales en que interface se cargarían?
3. Agregaríamos un submenú "Consultas" en el menú "Fichas y Consultas"?
4. Como y donde se verían todos los controles?

**Comment by rofaccess** [comment]
Según lo que estuvimos conversando por chat, Sería algo así?
1. Tenemos el menú "Fichas y Consultas" con los submenús "Fichas", "Consultas" , "Controles" y tal vez "Atención Profesional"
2.  Fichas, Consultas y Controles, cada uno son ABMs.

ABM DE FICHAS
1. Acá se agrega, edita y elimina fichas tal y como lo tenemos en la documentación, con la variación de que solo manejará los datos fijos (Ej. Antecedentes Postnatales).
2. Desde un ver Ficha, se podrá "Agregar Consulta" tal y como tienes "Agregar Control" en ver Consulta.
(Mi duda en este punto es, se te redirige a nueva consulta del abm de consultas o se abre un modal para cargar la consulta?)

ABM DE CONSULTAS
1. Acá se agrega, edita y elimina consultas, y, en un ver Consulta se puede "Agregar Control".

ABM DE CONTROLES
1. Acá se agrega, edita y elimina controles
Mi duda es: Si se va a agregar un control directamente desde este ABM, que datos vamos a especificar para saber a que consulta corresponde? Se especifica el paciente, la ficha y la fecha de consulta?  
Desde ver consulta podemos crear un control y será más fácil saber con que consulta va a ir relacionado cuando guardemos. Pero crear un control directamente del ABM de controles podría ser tedioso.

**Comment by rofaccess** [comment]
Otra cosa, el modelo de datos actual seguiría siendo válido no? 
Actualmente tenemos los datos fijos en la tabla Ficha..., las consultas en la tabla Consultas... y los controles en la tabla Ev_Co_Tr....

**Comment by Lesfig** [comment]
![consultanuevo3](https://cloud.githubusercontent.com/assets/6785488/14756949/c9c8382e-08bc-11e6-929d-b9410819b74d.png)
![consulshow4](https://cloud.githubusercontent.com/assets/6785488/14756950/ca196a1e-08bc-11e6-8f4b-1fdf4c25be2f.png)

**Comment by Lesfig** [comment]
![listaconsultas](https://cloud.githubusercontent.com/assets/6785488/14758939/888da250-08de-11e6-8ee3-bc3bcecee727.png)

**Comment by Lesfig** [comment]
tiempo 00:40m

**Comment by Lesfig** [comment]
@bordonwork @rofaccess @KariSanabria

**Comment by bordonwork** [comment]
@Lesfig por mi parte solo objeto el color del boton "Ver Ficha" debería ser un tono más claro de azul y solo mayúscula al principio de cada palabra para seguir con el estándar que definieron
