### ISSUE TITLE
Implementar el Modelo para Consultas

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#57]
Se requiere realizar el modelo para la tabla Consultas(y su detalle de tenerlo) definida en el modelo de datos, así como su migración y sus validaciones.

**Comment by rofaccess** [comment]
No alzé imagenes porque son muy pesadas, en la carpeta files, los que dicen consultas simplificadas es lo último que alzé, actualmente en la rama issue_57_modelo_consultas.
Todavía no actulicé lo referente a Pediatría y Odontología.

Básicamente establecí una sola tabla consultas como lo hablamos, y todo los campos de las fichas están en sus respectivas tablas de fichas. Eliminé las consultas y controles de las fichas (anteriormente teníamos consultas y controles especificos para cada ficha).

Ahora, cada ficha se representa en su respectiva tabla, exactamente igual a las fichas tal y como nos lo dieron, a excepción de los datos personales y encargados que están en otras tablas.

**Comment by louvelaz** [comment]
@rofaccess Este issue lo tengo que testear yo o lo van a ir discutiendo con los compañeros?

**Comment by rofaccess** [comment]
En el modelo de datos puse que cada ficha esta separada en tablas diferentes. 
En cada tabla de ficha, puse todos los campos que teníamos en las fichas, Ej. para la tabla fichas_fonoaudiológicas también puse motivo_consulta y evaluación, las cuales también van en la tabla consultas.
Básicamente en las tablas de fichas puse todos los datos de las fichas sin importar que hubieran o no campos parecidos en la tabla consultas (esto para no pensarlo mucho, si ponemos esto acá o allá). La tabla consultas representaría lo que se escribe detrás de las fichas en la realidad. 

@KariSanabria @louvelaz @Lesfig

**Comment by bordonwork** [comment]
@rofaccess de mi parte creo que es la unica forma de poder generalizar y agilizar su trabajo

**Comment by rofaccess** [comment]
Se decidió que todo lo referente a una consulta, Ej.: motivo_consulta, diagnostico, tratamiento, observación, etc. que se encuentren en las fichas, irán solo en la tabla consultas.

La tabla consultas y el modelo consultas ya están hechos, por eso cierro la tarea.
