### ISSUE TITLE
Implementar el feature Consultas

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#60]
En base a la descripción provista en el issue #24  y al diseño realizado en el issue #56  implementar el feature **Consultas**

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/consultas

**Comment by louvelaz** [comment]
@Lesfig 
- En los campos Motivo de Consulta, Evaluación y Tratamiento, ocurre el mismo problema reportado en el issue #55 sobre validaciones de limite superior que se definen en la interfaz con el limite superior de la base de datos, en los tres campos el limite en la bd es de 250, mientras que en la interfaz se definió 300, 300, 600 caracteres respectivamente

![msj](https://cloud.githubusercontent.com/assets/6853236/14935148/728dc1d0-0e95-11e6-82a2-501526c31400.jpg)
- Cuando se usa la búsqueda avanzada, al apretar el botón Filtrar, desaparece el recuadro de los filtros y debería permanecer allí como en las demás interfaces, y solo esconderse cuando se vuelva a apretar el icono de búsqueda avanzada

Sugerencia:
- Me parece redundante que en la búsqueda avanzada se pueda filtrar por Pacientes y por Área cuando en la búsqueda normal también se puede buscar por estos campos

**Comment by Lesfig** [comment]
@louvelaz Rodrigo tiene que resetear la base de datos, le voy a decir!! ahí ya funcionará lo de los limites, y lo del filtro voy a corregir.

**Comment by rofaccess** [comment]
http://cenade-test.herokuapp.com/consultas
