### ISSUE TITLE
Implementar las Fichas Clínica, Neurológica y Pediátrica 

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#61]
En base a la documentación descrita en el issue #24 realizar el diseño y la implementación para la ficha que será utilizada para Clínica, Neurología y Pediatría.

**Comment by rofaccess** [comment]
Para aclarar el contexto
![img-20160508-wa0005](https://cloud.githubusercontent.com/assets/2489653/15202205/367db5e4-17c6-11e6-995a-6c827548d726.jpg)

**Comment by rofaccess** [comment]
Testear en: 
- http://cenade-test.herokuapp.com/fichas_clinicos
- http://cenade-test.herokuapp.com/fichas_neurologicas
- http://cenade-test.herokuapp.com/fichas_pediatricas

Nota: En el show de fichas clinicos ya se muestran los tabs de consultas, esto debía ser para la tarea que esta en to do.

**Comment by louvelaz** [comment]
@rofaccess 
- Output de rails_best_practices
  ![cli 2](https://cloud.githubusercontent.com/assets/6853236/15247630/7f5318ae-18e3-11e6-9d4a-e289eaca9cd9.jpg)
  ![cli 3](https://cloud.githubusercontent.com/assets/6853236/15247631/7f58132c-18e3-11e6-8ecf-dc311ef677cf.jpg)
  ![cli](https://cloud.githubusercontent.com/assets/6853236/15247632/7f5a188e-18e3-11e6-84ed-64b0a7a52fa9.jpg)
