### ISSUE TITLE
Implementar la Ficha Psicopedagogía

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#62]
En base a la documentación descrita en el issue #24 realizar el diseño y la implementación para la ficha para Psicopedagogía

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/fichas_psicopedagogicas

**Comment by louvelaz** [comment]
@KariSanabria 
- En el campo Profesional de la Salud, no se muestran los profesionales de Psicopedagogía sino los de Fisioterapia 
- En Editar Ficha: El campo Paciente no se debería poder editar
- Output de rails_best_practices
  ![psico 2](https://cloud.githubusercontent.com/assets/6853236/15092374/f7cd0572-1435-11e6-8dd3-7f70bf05ab31.jpg)
  ![psico 3](https://cloud.githubusercontent.com/assets/6853236/15092376/f7d3a1b6-1435-11e6-93d1-88718954ed84.jpg)
  ![psico 4](https://cloud.githubusercontent.com/assets/6853236/15092375/f7d2f432-1435-11e6-9940-b7c96c21c134.jpg)
  ![psico 5](https://cloud.githubusercontent.com/assets/6853236/15092377/f7d62170-1435-11e6-9eca-d8285f40d764.jpg)
  ![psico 6](https://cloud.githubusercontent.com/assets/6853236/15092378/f7db0a96-1435-11e6-89f4-d0d267243b41.jpg)
  ![psico 7](https://cloud.githubusercontent.com/assets/6853236/15092379/f7dc08ba-1435-11e6-893e-a1e5e2665796.jpg)
  ![psico 8](https://cloud.githubusercontent.com/assets/6853236/15092380/f7f091d6-1435-11e6-81f3-cccc4b2a92bf.jpg)
  ![psico 9](https://cloud.githubusercontent.com/assets/6853236/15092381/f7f62e66-1435-11e6-890d-8c6643ffde78.jpg)
  ![psico](https://cloud.githubusercontent.com/assets/6853236/15092382/f7f9bcd4-1435-11e6-86d4-f62381ac782d.jpg)

**Comment by KariSanabria** [comment]
Commit de **Fecha**:09/04

**Comment by rofaccess** [comment]
Nota: Actualmente, al editar las fichas ya existentes en heroku, no aparece seteado el profesional de la salud. Esto es, porque antes se los había seteado con profesionales de fisioterapia y no fonoaudiología, y, el select, ahora trae solo de fonoaudiología.
