### ISSUE TITLE
Implementar la Ficha Nutricional Niños

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#64]
En base a la documentación descrita en el issue #24 realizar el diseño y la implementación para la ficha para Nutricional Niños

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/fichas_nutricionales_pediatricas

**Comment by louvelaz** [comment]
@Lesfig 
- Output de rails_best_practices
  ![nutri 2](https://cloud.githubusercontent.com/assets/6853236/15096574/5b60aa3e-14cd-11e6-8001-c16a4b08d6aa.jpg)
  ![nutri 3](https://cloud.githubusercontent.com/assets/6853236/15096575/5b63b8b4-14cd-11e6-84fa-ba3579057bff.jpg)
  ![nutri 4](https://cloud.githubusercontent.com/assets/6853236/15096576/5b6756f4-14cd-11e6-9a8e-caafdfae25d4.jpg)
  ![nutri 5](https://cloud.githubusercontent.com/assets/6853236/15096578/5b6f580e-14cd-11e6-9875-d58016d89244.jpg)
  ![nutri](https://cloud.githubusercontent.com/assets/6853236/15096577/5b6cd3ae-14cd-11e6-9dfb-56d3c8aa7d09.jpg)
