### ISSUE TITLE
Implementar la ficha Nutricional Adultos

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#65]
En base a la documentación descrita en el issue #24  realizar el diseño y la implementación para la ficha para Nutricional Adultos

**Comment by Lesfig** [comment]
el cambio de in progress a to review fue sin querer..

**Comment by rofaccess** [comment]
Testear en: http://cenade-test.herokuapp.com/fichas_nutricionales_adultos

**Comment by louvelaz** [comment]
@Lesfig 
- Hay mensajes que salen en ingles
  ![msj](https://cloud.githubusercontent.com/assets/6853236/15137978/e43221a6-165a-11e6-912e-a653c794fbc4.jpg)
- No guarda el campo "Nº de Hijos" en la bd
- El Titulo "Familiares:" cambia de tamaño en el show de la ficha
  ![new](https://cloud.githubusercontent.com/assets/6853236/15137984/f3c67cac-165a-11e6-886a-9e4bb044260a.jpg)

![show](https://cloud.githubusercontent.com/assets/6853236/15137989/faaa9f4e-165a-11e6-8901-e68c06440203.jpg)
- Output de rails_best_practices
  ![nutri 2](https://cloud.githubusercontent.com/assets/6853236/15138002/0c73473a-165b-11e6-9a60-903c00285a93.jpg)
  ![nutri 3](https://cloud.githubusercontent.com/assets/6853236/15138003/0c8d5a12-165b-11e6-81ec-5abea12aff1c.jpg)
  ![nutri 4](https://cloud.githubusercontent.com/assets/6853236/15138004/0c909b32-165b-11e6-906d-b699091ef186.jpg)
  ![nutri 5](https://cloud.githubusercontent.com/assets/6853236/15138005/0c93d982-165b-11e6-8cd6-518facc06113.jpg)
  ![nutri](https://cloud.githubusercontent.com/assets/6853236/15138006/0c9ac40e-165b-11e6-96b9-6e15e56a41f1.jpg)

**Comment by carlosleite** [comment]
@Lesfig 
**El crear una ficha:**
- El campo de numero de hijos no se guarda.
- El campo numero de hijos muestra un mensaje en ingles al ingresar ”-” en el campo
  ![screenshot 2016-05-29 14 16 18](https://cloud.githubusercontent.com/assets/1580982/15635302/f97fdd20-25a8-11e6-9155-2dd64cb11fba.png)

**Al editar una ficha:**
- Modificando cualquier campo retorna un error 500
  ![screenshot 2016-05-29 14 22 27](https://cloud.githubusercontent.com/assets/1580982/15635303/04740a12-25a9-11e6-87f7-e39deac56587.png)

**Comment by Lesfig** [comment]
No hay ningún commit relacionado porque lo arreglé mientras implementaba el issue #70

**Comment by Lesfig** [comment]
Modificaciones realizadas durante la implementación de reportes
