### ISSUE TITLE
Implementar el ABM de consultas para la Ficha Nutrición Pediátrica 

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#67]
Se requiere diseñar e implementar el abm para las cosultas de la Ficha _Nutrición Pediátrica_

**Comment by rofaccess** [comment]
Cambio a to review, para que se arregle ese problema con consultas que se encontró hoy en clase

**Comment by louvelaz** [comment]
@Lesfig 
- Nuevo Control: Se debe mostrar el mensaje de error de campo obligatorio en el campo Profesional de la Salud. Solo tira error en la consola, y en la interfaz no se muestra nada
  ![error](https://cloud.githubusercontent.com/assets/6853236/15447037/e680c2ce-1f00-11e6-8bf1-27c3fb19dac2.jpg)
- Nueva Consulta: En el campo Fecha, la fecha deberia ser menor o igual a la fecha del sistema
