### ISSUE TITLE
Implementar el feature Consulta Nutricional Niños

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#69]
Se requiere diseñar e implementar la vista consulta para la Ficha de Nutricional Niños #64

**Comment by rofaccess** [comment]
@bordonwork @Lesfig 
Creo que esto ya se esta implementado en #67
Nutricional Niños y Nutricion Pediátrica son lo mismo

**Comment by Lesfig** [comment]
Sii es la misma @bordonwork. XD

**Comment by bordonwork** [comment]
@Lesfig ok
