### ISSUE TITLE
Realizar ABM de Usuarios

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#7]
Depende del issue #3 y #9
Se requiere generar el ABM para el modelo Usuarios. Esto incluye:
- Agregar un usuario.
- Editar un usuario.
- Eliminar un usuario(borrado ocioso).
- Listar usuarios.
  Los formularios deben estar validados. Ver [jquery-validation](https://github.com/jzaefferer/jquery-validation)
- Cuando se termine el abm de empleados, se deberá actualizar el
  abm con los datos  correspondientes a empleado (Tarea 7).
- Borrar un usuario, no borra al empleado.

**Comment by rofaccess** [comment]
**Testear** en: http://cenade-test.herokuapp.com/usuarios

**Nota:**
- Los username son únicos, si se intenta guardar un username que ya existe, mostrará un mensaje de no se ha podido guardar. Habría que agregar una validación que consulte si el nombre de usuario ya existe antes de enviarlo, otra posibilidad sería que el mensaje sea más especifico del porque no se guardo.
- El Select en crear, solo lista los empleados que no tienen usuario, ya que la política es y será un usuario por empleado.

**Comment by louvelaz** [comment]
@KariSanabria Estoy queriendo testearlo pero no me esta funcionando el botón Agregar Usuario, ni en Firefox ni en Chrome

**Comment by rofaccess** [comment]
Resetee los datos de la bd en Heroku y anduvo de vuelta.
Rompe de vuelta por favor, para encontrar los pasos que generan el problema y hallar su origen.

**Comment by louvelaz** [comment]
@KariSanabria Los mensajes de error deben especificar el porque no se guardo. Ej: Este nombre de usuario ya existe

![usuario test cenade 6 cambiar error](https://cloud.githubusercontent.com/assets/6853236/14247678/e962b0fc-fa3d-11e5-9d63-76be147ab09e.jpg)

**Comment by bordonwork** [comment]
@louvelaz y @KariSanabria esa mejora se introducirá en el Sprint 4 puesto que se realizarán cambios en la vista de usuarios
