### ISSUE TITLE
Implementar el feature Consulta Nutricional Adultos

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#70]
Se requiere diseñar e implementar la vista consulta para la Ficha Nutricional Adultos #65

**Comment by Lesfig** [comment]
La referencia del último commit es para el issue #65, y no para éste issue

**Comment by carlosleite** [comment]
@Lesfig , @rofaccess 
- Cuando se ingresa alguna fecha con año cero sale un error de rails.
  ![screenshot 2016-05-29 14 22 27](https://cloud.githubusercontent.com/assets/1580982/15845102/c4344b2e-2c3d-11e6-9086-39b9ae5b3dfd.png)

Pasa en varios formularios.
En Consulta de fonoaudionlogia guardó sin fecha(al ingresar fecha 01/01/0) y ahora ya no se puede acceder: http://cenade-test.herokuapp.com/consultas?area_id=3

**Comment by carlosleite** [comment]
@rofaccess , @Lesfig probe las demas fichas y consultas. Este es el resultado al ingresa como fecha '1/1/0' (es muy poco probable que alguien se equivoque una fecha asi pero pasa):

Consultas:
    - Clinico: retornó error y ya no se puede acceder al listado
    - Fisioterapia: retornó error y ya no se puede acceder al listado
    - Fonoaudiologia: retornó error y ya no se puede acceder al listado
    - Neurologia: retornó error y ya no se puede acceder al listado
    - Nutricional adulto: retornó error.
    - Nutricional pediatrica: retornó error.
    - Odonto: retornó error.
    - Psicopedagogia: retornó error y ya no se puede acceder al listado
    - Pediatria: retornó error y ya no se puede acceder al listado

Fichas:
    - Clinico: retornó error
    - Fisioterapia Adulo: retornó error.
    - Fisioterapia Pediatrica: retorna error sin importar que la fecha sea la correcta.***
    - Fonoaudiologia: retornó error
    - Neurologia: retornó error
    - Nutricional adulto: retornó error.
    - Nutricional pediatrica: retornó error.
    - Odonto: retornó error.
    - Psicopedagogia: retornó error
    - Pediatria: retornó error

**Sugerencia:**  Si estan usando bootstrap-datepicker pueden configurar el valor por defecto de la opcion [startDate](https://bootstrap-datepicker.readthedocs.io/en/stable/options.html#id6); entonces desde el cliente ya no se va una fecha invalida.
