### ISSUE TITLE
Actualizar la ficha Fisioterapia Adultos

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#72]
Se requiere actualizar la vista Ficha Fisioterapia Adultos #54 para que se  puedan ver las consultas asociadas.

**Comment by louvelaz** [comment]
@rofaccess 
- Output de rails_best_practices
  ![fisio](https://cloud.githubusercontent.com/assets/6853236/15246883/31bb4922-18de-11e6-889c-edc1c25a716c.jpg)
