### ISSUE TITLE
Actualizar la ficha Fisioterapia Niños

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#73]
Se requiere actualizar la vista Ficha Fisioterapia Niños #55  para que se  puedan ver las consultas asociadas.

**Comment by rofaccess** [comment]
@bordonwork @Lesfig 
Creo que ya se hizo en #66, actualmente está en Ready to Test

**Comment by Lesfig** [comment]
Ésta ya implementé XD @bordonwork

**Comment by bordonwork** [comment]
@Lesfig ok
