### ISSUE TITLE
Implementar el Feautre Historial Clinico

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#76]
1. Se implementará un historial clínico por área.
2. Se accederá al historial clínico, a través del menu Fichas y Consultas, submenu Historial Clínico
3. Al acceder se tendrá el sidebar o menú lateral que tendrá todas las áreas, tal cual en fichas. 
4. Por cada área se tendrá una lista de pacientes especificando los datos básicos (nombre, apellido, ci, direccion, telefono, fecha de ingreso). 
5. Básicamente se listarán los pacientes que tengan ficha en el área especificada.
6. Por cada registro de paciente se tendrá la opción ver historial, que mostrará primero la ficha del área y a continuación todas las consultas hechas en el área especificada sin posibilidad de edicíon (A diferencia del show de fichas, el historial mostrará todas las consultas).

Nota: 
Esta parece ser la manera más simple de encararlo. 
En internet se encuentran formatos que engloban todas las áreas  (Ej. http://www.mspbs.gov.py/documentacion/index.php?f=INSTRUCTIVO%20HCFINAL%20.pdf). Otros formatos son especificos por área.

**Comment by rofaccess** [comment]
El commit anterior es del día Viernes 13 de Mayo a las 21:40 horas.

Mi internet no me funcionaba y por eso no pude alzar.

**Comment by rofaccess** [comment]
Testear en: 
http://cenade-test.herokuapp.com/welcome/index_historial

**Comment by carlosleite** [comment]
@rofaccess 
- No es evidente que los titulos son clickeables. Se podria agregar cursor: pointer; a la cabezera de los paneles
- Deberia abrirse el contenido de cada panel al hace click (no doble click)

**Comment by rofaccess** [comment]
Hecho. 
No hay ningún commit relacionado porque lo arreglé mientras implementaba #77
