### ISSUE TITLE
Implementar el feature Atención Profesional

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#77]
En base a la documentación provista en el issue #23 realizar el diseño y la implementación del feature **Atención profesional**

**Comment by rofaccess** [comment]
Cambié la estimación, porque en el #76 ya estoy por rebasar los 30, y este es parecido pero con más extras.

**Comment by rofaccess** [comment]
@carlosleite @Lesfig @KariSanabria @bordonwork 
Gente, recién pude terminar atención profesional para nutrición. Esta en Heroku.
En el sidebar deberan elegir un doctor del area de nutricion (se puede buscar por nombre, apellido o area) y una fecha

Se puede agregar una nueva consulta pediatrica y/o adulto y un control cuando el turno del paciente esta pendiente. Si no es pendiente no se puede agregar nada.

Solo se setea como atendido con el icono ok (el dibujito de bien al lado de los nombres). Osea que, si se recarga de nuevo los datos del paciente haciendo click sobre el paciente en el sidebar, se podrán agregar indefinidamente controles y/o consultas. No mejoré esto ya que requerirá más trabajo y ademas confío en que el usuario no hará macana (Osea que agregara un control o consulta y ya seteará como atendido)

**Comment by rofaccess** [comment]
Si se crea una consulta o control desde atención profesional, el turno ya se setea como atendido.
Testear en:
http://cenade-test.herokuapp.com/atenciones_profesionales

**Comment by rofaccess** [comment]
Ya está en Heroku. 
Lo muevo de nuevo a To Do porque al probarlo en Heroku me di cuenta de que me faltó algo (Si el paciente no tiene por lo menos una consulta y control, no se muestra el formulario de crear nueva consulta o control).

**Comment by carlosleite** [comment]
@rofaccess , cual es la condicion para que un paciente aparezca en la pagina de atencion profesional? Selecciono fechas, profesionales pero no aparece ningun paciente que tienen fichas/consultas/controles.

**Comment by rofaccess** [comment]
@carlosleite El paciente debe tener turno con el profesional y fecha de consulta especificados.

Al seleccionar un profesional y una fecha, se lista los pacientes que tengan turno con el profesional en la fecha especificada.

**Comment by carlosleite** [comment]
@rofaccess , esta bien que se pueda marcar como atendido a un turno de un paciente que no tiene ficha?. No encontré nada en la doc acerca de esto.

![screenshot 2016-06-17 19 45 13](https://cloud.githubusercontent.com/assets/1580982/16167535/31dfd722-34c4-11e6-80e4-5cf1beda29ce.png)

**Comment by rofaccess** [comment]
@carlosleite  Así luego funciona.

Dependerá del buen uso que le de el usuario, ya que se espera que vaya a la seccion de fichas a crear la ficha, y que después setee al paciente como atendido.

Este feature puede mejorar más todavía, se podría crear la ficha desde aquí mismo o por lo menos mostrar un link, también se podría agregar esa restricción que mencionas. En su momento me enfoqué en hacer que fuera lo más funcional posible.
