### ISSUE TITLE
Realizar ABM de Empleados

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#8]
Depende del issue #4 y #10
Se requiere generar el ABM para el modelo Empleados. Esto incluye:
- [x] Agregar un empleado.
- [x] Editar un empleado.
- [x] Eliminar un empleado(borrado ocioso).
- [x] Listar empleados.
- [x] Los formularios deben estar validados. Ver [jquery-validation](https://github.com/jzaefferer/jquery-validation)

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 24.25h (24h y 15m)

**Comment by rofaccess** [comment]
@louvelaz 
Ingresar a: http://cenade-test.herokuapp.com/empleados
Notas:
- La interfaz no es la misma que el diseño original, traté de mejorarlo un poco.
- Mismo usuario y contraseña de siempre.
- Si al hacer click en alguna fila de la tabla no te muestra los datos del empleado, se debe recargar la página y funcionará. Este detalle me ocurrió en mi maquina local y en heroku, creo que es problema del WebServer Puma que uso para Heroku. Ya que en la rama development uso WEBRick y no pasa eso.

**Comment by louvelaz** [comment]
@rofaccess 
- En la fecha de nacimiento se tiene  que poder seleccionar el mes y el año sin tener que ir atrás con las flechas

![seleccionar fecha](https://cloud.githubusercontent.com/assets/6853236/13802309/4e5bd058-eb19-11e5-9cfa-6b81ff2bab31.jpg)
- CI debería aceptar a partir de 4 caracteres
- El limite inferior de Nombre y apellido  debería ser 3
- Cuando se ingresa una dirección con el limite superior del campo, la grilla se desarregla, y al deslizar a la derecha la barra de menú superior ya no se muestra

![ver](https://cloud.githubusercontent.com/assets/6853236/13802327/6d62ede2-eb19-11e5-9aa0-4f90514e60f4.jpg)

![ver 2](https://cloud.githubusercontent.com/assets/6853236/13802335/76f01ea2-eb19-11e5-9bed-1c7dd7728593.jpg)

![ver 3](https://cloud.githubusercontent.com/assets/6853236/13802339/806d2bc8-eb19-11e5-9b80-ca8fcaa0cf78.jpg)

Sugerencias:
- Se podrían no mostrar algunos campos para que no se vean tan encimados
- Al haber muchos campos de color negro, el color de los mensajes de las validaciones se confunde un poco con ellos, se podría poner un color mas claro

**Comment by rofaccess** [comment]
- La fecha ya no despliega nada, ya que es una función que no aporta ningún valor.
- Se agregó limite inferior a ci, nombre y apellido
- Si la direccion es muy larga, la misma se corta
- El limite superior para dirección es ahora 125, el anterior era muy largo
- Se quitaron algunos campos de la lista
- Las validaciones ahora resaltan más

**Comment by rofaccess** [comment]
En mi commit puse "Issue#8" y no "Issue #8" tal vez por eso el commit no se relacionó con esta tarea.

**Tiempo Utilizado:** 02h00m
