### ISSUE TITLE
Realizar manual de usuario para Usuarios

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#80]
Se requiere hacer la estructura y la documentación para el manual de usuario del feature Usuarios.
Debe contener las siguientes partes:
- Titulo del feature. Ej.: **_Usuario_**
- Titulo de la acción. Ej.: **_Nuevo Usuario_**
- Pantallas
- Guía paso a paso (con imágenes incluidas) para realizar cada acción permitida en el feature.
- Indicar advertencias o sugerencias para cada acción. Ej.: **_Si el nombre de usuario ya existe saldrá un mensaje de error._** 

Se debe utilizar un lenguaje en 3ra persona. Ej.: **_Para crear un nuevo usuario el usuario deberá ..._**

Obs.: Incluir estimativa del ticket

**Comment by KariSanabria** [comment]
@Lesfig @rofaccess @bordonwork Espero sugerencias sobre el manual, la misma tiende a cambios.

**Comment by rofaccess** [comment]
Esta todo ok.

**Comment by bordonwork** [comment]
Todo ok

**Comment by bordonwork** [comment]
@KariSanabria 2 de 3, cerrado
