### ISSUE TITLE
Mejorar la vista Imprimir

### ISSUE THREAD

**Issue by KariSanabria** [rofaccess/CENADE#81]
Verificar que todas las vistas de Impresión estén actualizadas y correctas.

**Comment by Lesfig** [comment]
fecha 03/06: tiempo 01:30m

Pd.: no especifiqué el issue en mi commit

**Comment by carlosleite** [comment]
@rofaccess , @Lesfig no se que exactamente cambió. Todas impresiones que veo parecen estar bien.

 Una duda, al imprimir una ficha no se imprime las consultas de la misma. Esta bien eso?

**Comment by rofaccess** [comment]
@carlosleite Había unas impresiones que no tenían la misma estructura que las demás, Leslie arreglo eso.
Creo que todas las impresiones funcionan y tienen ya el mismo formato, por lo que esta tarea ya se puede cerrar.

Respecto a imprimir ficha, lo hicimos así luego.
