### ISSUE TITLE
Diseñar el ABM de Usuarios

### ISSUE THREAD

**Issue by bordonwork** [rofaccess/CENADE#9]
Se requiere hacer el diseño para las vistas del ABM de Usuarios, esto incluye:
- Nuevo(y editar) usuario.
- Listar usuario.

**Comment by rofaccess** [comment]
**Listado de Usuarios**

![screenshot from 2016-03-05 17-39-50](https://cloud.githubusercontent.com/assets/2489653/13550299/6d0eb0b0-e2f9-11e5-8ae1-f38929b40277.png)

**Nuevo Usuario (Valido también para editar)**

![screenshot from 2016-03-05 17-44-10](https://cloud.githubusercontent.com/assets/2489653/13550331/002c9aba-e2fa-11e5-8c84-333da4caa7bd.png)

**Comment by rofaccess** [comment]
**Breve Descripción**
**Listado de Usuarios**
1. En la interfaz donde se lista el usuario se puede buscar por cualquier campo de la tabla.
2. Los datos del personal como nombre, apellido, direccion, de la tabla solo son para brindar mas detalles del usuario en cuestion
3. La lupa con el simbolo "+" deberá desplegar una sección de busqueda avanzada (Esto se diseñara e implementará en algún momento más adelante)
4. El botón agregar usuario abrirá un formulario para cargar los datos a través de ajax

**Agregar Usuario**
1. Para agregar usuario, primero se debe especificar el C.I. de un empleado, previamente registrado en el sistema.
2. Una vez especificado el C.I. se muestran datos básicos del personal, así como las opciones para establecer nombre de usuario, contraseña y roles.

Para este primer sprint, se puede ignorar lo referente a empleados o personal y centrarse unicamente en la información de usuario.

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 2 Horas

**Comment by louvelaz** [comment]
@rofaccess Los roles de usuario deberían ser radiobutton no checkbox, porque un usuario no puede tener 2 roles a la vez, los doctores solo son doctores, lo mismo con la secretaria y el admin.

**Comment by rofaccess** [comment]
La razón de que se le pueda asignar más de un rol a un usuario es para brindar mayor flexibilidad.
Por ejemplo: Supongamos que tenemos dos roles: Doctor y Gestionador de Turnos.
El  rol Doctor puede acceder a todos los items del historial médico.
El Gestionador de Turnos solo puede acceder al Item Turnos en el menú principal.
Ahora supongamos que por a o b motivo se requiera que un persona que trabaja como doctor ( y que obviamente tenga un rol doctor) pueda acceder a gestionar turnos.
Para hacer esto se podría modificar los permisos del rol Doctor pero esto afectaría a todos los doctores, y queremos que solo un doctor puede gestionar turnos.
También se podría crear un nuevo rol "Doctor que gestiona turnos" lo que implica que se deben establecer los permisos de un rol doctor y de un gestionador de turnos.
Y después tenemos la opción más eficiente, simplemente asignarle a una persona que ya tiene un rol doctor, otro rol que se llama gestionador de turnos. Y si en algún momento no se quiere mas que esta persona gestione turnos, solo se le quita ese rol.
Espero haber sido claro con la explicación

**Comment by rofaccess** [comment]
![screenshot from 2016-03-05 23-57-42](https://cloud.githubusercontent.com/assets/2489653/13552026/22f12a6e-e32e-11e5-9721-ace59aa73def.png)

Como no se sabe cuantos roles podría cargar el administrador del sistemas, es mejor usar un select que permita seleccionar más de un rol. También, si se necesita otro rol, se lo agrega haciendo click con el icono + que muestra un modal para establecer el rol (después en la sección de permisos se le podrá agregar los permisos al nuevo rol creado)
El select sería similar al siguiente:
![screenshot from 2016-03-06 00-24-35](https://cloud.githubusercontent.com/assets/2489653/13552121/db125c64-e331-11e5-8f15-e77e5feaf242.png)
Fuente: https://select2.github.io/examples.html

**Comment by rofaccess** [comment]
**Tiempo Utilizado:** 1 hora

**Comment by louvelaz** [comment]
@rofaccess Entiendo tu punto, pero en el sistema de la CENADE operan solo 3 actores, es la secretaria la que se encarga de gestionar turnos según el documento. Podrían tener varios roles los actores y en ese caso habría que actualizar el documento.

**Comment by rofaccess** [comment]
La política actual del CENADE dice que es la secretaria, pero tal vez no siempre sea así, no sabemos como cambien las políticas a largo plazo, o bien, tal vez se lleguen a requerir cierta flexibilidad en algunos casos especiales.
En la documentación se tienen 3 actores, pero, actores no son lo mismo que roles, además la documentación no especifíca una clase rol, lo cual hay que agregar en la documentación.

Tu punto es válido, el mío también, propongo que lo dejes como en ready to test y que lo sometamos al arbitraje de los project owner.

**Comment by louvelaz** [comment]
@rofaccess Yo se que los actores no son lo mismo que roles, el documento no es definitivo tampoco, va a sufrir muchos cambios. Por eso puse mas arriba para actualizarlo y agregarle tu modificación. Voy a dejar en Ready To Test para que los project owner y el project leader decidan.

**Comment by bordonwork** [comment]
@rofaccess y @louvelaz por mi parte creo que si solo existen tres roles estáticos que fueron diseñados en base a los tres actores existentes no veo necesidad de permitir seleccionar mas de un rol por actor, en cambio si los roles serán dinámicos si es importante permitir mas de un rol por actor. @afocampos y @mirtara sus opiniones?

**Comment by bordonwork** [comment]
Queda decidido un rol por usuario
